### ISSUE TITLE
Update is hanging

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-syno-spk#100]
I see this dialog for more than an hour:

![image](https://user-images.githubusercontent.com/1847437/31311454-b1e4f69a-abac-11e7-9e82-0843c348c2c8.png)

First of all, 

https://github.com/openhab/openhab-syno-spk/releases/download/2.1.0.008-DSM6/openHAB-2.1.0.008-DSM6-syno-noarch-0.001.spk

has been used to install it initially and then I took

https://github.com/openhab/openhab-syno-spk/releases/download/2.2.0.006-SNAPSHOT/openHAB-2.2.0.006-SNAPSHOT-syno-noarch-0.001.spk

for an update.

**Comment by cniweb** [comment]
This way is not supported at the moment.
Uninstall the old version and install the new.
Update is not working, sorry!
We work on a stable version for 2.2.0-SNAPSHOT branch.

**Comment by thopiekar** [comment]
Ok, we can close it then.

**Comment by cniweb** [comment]
I leave it open, because the update should work once

**Comment by calle2010** [comment]
I saw this issue too late. Did the update on my one week old DS116 from 
openHAB-2.1.0.011-syno-noarch-0.001.spk (which didn't work for me)
to 
openHAB-2.2.0.007-SNAPSHOT-syno-noarch-0.001.spk

I had an SSH session open in directory 
openHAB-2.2.0.007-SNAPSHOT-syno-noarch-0.001.spk

As the update was not progressing, I did an ```ls``` command. Result
```-sh: /usr/bin/ls: No such file or directory```

Horrified, I pressed the power button on the system. It blinks, but it doesn't shut down.

Did I just brick my new DS116?

**Comment by calle2010** [comment]
Another thing: The Web UI of the DS116 doesn't show anymore, only a message like "Synology, sorry, page not found" (for me in German) coming up.

**Comment by calle2010** [comment]
I had to do a reset of my DS116. Assistant offered me a "migration". Data and configuration is back, but some things still don't work (File Station doesn't show shared folders, Video Station doesn't run).

I uninstalled openhab2 package. Now I see a directory ```/volume1/@appstore/openHAB2-backup-201710/userdir``` which looks like a copy of the root directory of the DS116, including soft links usr/bin and usr/lib. If this was created/tried to be removed during the upgrade of the SPK I could imagine that it caused the issues I faced before.

Sorry, I won't be investigating further and use my DS116 as a file server in the future, nothing else.

**Comment by calle2010** [comment]
If I may guess:

https://github.com/openhab/openhab-syno-spk/blob/8a665337bf8cf5d0be5a628045feb0e7e0a40a0f/scripts/installer.sh#L385

This line may be the failure: if LINK_FOLDER for some reason is empty it would try to move all files from root directory to userdir in the backup folder. It should be checked that LINK_FOLDER exists to make sure this is not an empty string.

**Comment by cniweb** [comment]
The update still does not work 100%. We're still working on it!
@SchoppAx Can you say something about this?

**Comment by SchoppAx** [comment]
Mh, if the link folder variable is empty...

I have added a check.

I will check the old packages 2.1.0.008 and 2.1.0.011, maybe there is everything wrong with the symbolic link :-/

**Comment by cniweb** [comment]
OK, I close this issue.
A new release is already planned.
