### ISSUE TITLE
Expaination how the SPK works

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-syno-spk#101]
Could you explain how the SPK works?
I installed openHAB to the home directory of the openHAB2 user and found this:
![image](https://user-images.githubusercontent.com/1847437/31334658-73b1ddea-acef-11e7-84a9-748608b3c8ed.png)
Is it a kind of chroot we are using? If so, why?

**Comment by cniweb** [comment]
@SchoppAx can you explain how the SPK works with the home directory?

**Comment by thopiekar** [comment]
Also I would really like to understand how SPK works in general. Something like a brief summary, so I check get an kickstart on this.
Before I had updates working on my QPKG package, but my QNAP made a lot of trouble so I got my money back after a year and now I'm on the Synology trian.
Maybe we can get something awesome working.. At least doing some cleanups, so the package does not mention openHAB2 anymore. I remember @kaikreuzer got itchy eyes, when he saw similar things in on the QPKG project 😄

**Comment by SchoppAx** [comment]
For the beginning you can look inside the DSM Developer Guide: https://developer.synology.com/download/developer-guide.pdf
You don't need the build environment. So you can start on page 45.

The minimal source structure is like:
YourPackageSource/
        ├── INFO
        ├── LICENSE
        ├── PKG_DEPS
        ├── PACKAGE_ICON.PNG
        ├── PACKAGE_ICON_256.PNG
        ├── scripts/
         |    ├── postinst
         |    ├── postuninst
         |    ├── postupgrade
         |    ├── preinst
         |    ├── preuninst
         |    ├── preupgrade
         |    └── start-stop

There is a good picture of the building workflow on page 16.
To Build a Package you only have to:
`cd /YourPackageSource`
`tar -cvf YourPackageSource-0.001.spk *`

All you need to know about the package structure are described in the `Package Structure` section, page 45 - 71.
And about the UI wizard and files on page 72 - 84.

**Comment by cniweb** [comment]
You can join our german synology openhab chat at skype:
https://join.skype.com/jUy7dOUy2z7P

**Comment by cniweb** [comment]
@thopiekar You have skype?

**Comment by thopiekar** [comment]
Yes, I have. Sorry that I was not responding for a long time.
Very busy with my graduation and I'm far way from my NAS at the moment.

Will join the room soon.
