### ISSUE TITLE
Provide folder USERDATA as well in \public\openHAB2\.

### ISSUE THREAD

**Issue by loovanloon** [openhab/openhab-syno-spk#103]
ENHANCEMENT: 
For backup and restore purposes of the installation configured through the paper UI I think it is usefull to provide access to the USERDATA folder as well in the \public\openHAB2\ folder

**Comment by cniweb** [comment]
The folder USERDATA should also be linked via
`/public/openhab2/`
or
`/smarthome/openhab2/`
or
`/var/services/homes/openhab2/`

**Comment by SchoppAx** [comment]
@cniweb tell me if I'm wrong, but i think the "innovation" of the openhab2 config files (userdata) are, that they can be full managed with the PaperUI. So the user doesn't need to change the config files itselfs.

**Comment by loovanloon** [comment]
@SchoppAx  The issue is not _changing_ the files, but _backing up_ the files.

In OH2 there are indeed 2 ways of configuration:
1. through config-text files in ./openhab2/conf/.  (OH1 style)
2. though paper UI, stored in JSONDB in ./openhab2/userdata/.

Hence to (easily) backup your configuration made through the PaperUI (and stored in JSONDB) you also need easy access to  ./openhab2/userdata

**Comment by aurelio1** [comment]
While the PaperUI can make several things easier, it is far from being that powerful to replace manual editing of config files. But the config files are already linked in the public folder so it is no issue at all editing them from DSM.
If you set up a new device, from my experience it happens often that you have to check the logfiles or changing some log settings (these are also in the userdata folder). I did the link myself, but for sure it would be useful if the SynOH2 installation linked the userdata folder to the public as it does with the config folder. And for backup also, as you write. It is useful anyway.

**Comment by cniweb** [comment]
Another case would be the update. Because the update does not work, but only an uninstall and install. The data will be deleted.

**Comment by cniweb** [comment]
@loovanloon and @aurelio1 I add the userdata folder, is this ok (see my commit)?

**Comment by aurelio1** [comment]
@cniweb Great, thank you! I just wondered why it is necessary to remove the single userdata subdirectories such as tmp, log, logs and cache. Why didn't you do it at once, as with the conf directory that includes all subdirectories? I did it manually up to now and moved the directory and linked to it in one operation.

**Comment by cniweb** [comment]
@aurelio1 Because the directories:
`config`, `etc`, `jsondb` and `kar`
contain data that must be retained during the update.

**Comment by loovanloon** [comment]
Where can I download the SPK that contains the change?

**Comment by cniweb** [comment]
I think I have time this sunday...

**Comment by cniweb** [comment]
@loovanloon New version is released:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.2.0.008-SNAPSHOT
