### ISSUE TITLE
Old issue?

### ISSUE THREAD

**Issue by volcore79** [openhab/openhab-syno-spk#105]
Hi all,

it's my first installation, i seem to get an "old" error: "User home service not enabled". I installed Java "ejdk1.8.0_144" (1.8.0_144-0044) via PCLoadLetter Packetsource and it is running (i also tried the Java 8 installation of synology - same problem).

I am using DSM 6.1.3 - 15152 Update 7 on DS214se. I tried the installation of openHAB-2.2.0.007.

Does anyone know how i can solve my problem?

Volker

**Comment by SchoppAx** [comment]
Hi Volker,

please enable the User Home Service.
Control panel -> User -> Advanced -> Check "Enable user home service"

**Comment by cniweb** [comment]
@volcore79 can I close this issue?

**Comment by volcore79** [comment]
Installation works, thanks! Yes, @cniweb
