### ISSUE TITLE
Installation script doesn't mention to add USERDATA map during installation instruction.

### ISSUE THREAD

**Issue by loovanloon** [openhab/openhab-syno-spk#110]
Add the installation instruction about the USERDATA map to the end-user installation instructions during installation of the package.

During installation it is instructed to the end-user that if the CONF and ADDONS map exist in the public\openHAB2 map, that the installation will make a link to these maps.  The instructions only mentions these these two maps and it doesn't mention the USERDATA map. (on several times during the installation: at the beginning and also at the package Info-screen in syno package center when the installation is finished)

**Comment by cniweb** [comment]
Fixed with #115
