### ISSUE TITLE
Make Ports configurable on installation

### ISSUE THREAD

**Issue by BergmDaniel** [openhab/openhab-syno-spk#116]
Hi,
i want to install OH2 on my DS415play but i get every time the "Port undefined" Error. I had tryed to installation for a long time with Version 2.0.0.009. In the current versions the user will normaly ask in the Setup for the Ports and direction. But in my case there comes no fill out fields in the setup, directly after choosing the *.spk file the error will shown me. I think the DS try to use the old installfiles from the old version. I hope someone can halp me to fix the issue.
I have tryed with the following versions, it is all the same:
openHAB-2.2.0.007-SNAPSHOT-syno-noarch-0.001.spk
openHAB-2.2.0.008-SNAPSHOT-syno-noarch-0.001.spk
My DS415Play runs on DSM 6.1.3-15152 Update 8
Thanks for ideas
Daniel

**Comment by jaghatei** [comment]
I had same error which was caused by a different package using the SSL port 8443. Syno installer seems to check in config files in /usr/local/etc/services.d/ if any other installed package uses the ports the current installation requires. In my case it was the CardDAV server.
If so the installation dialogs will not appear, but above error.
Workaround: reconfigure the other package to port different than 8443 then install OH. On your need change port in OH and configure other package back.
But as a better solution the OH package installer should ask for SSL port also.

**Comment by adromir** [comment]
I also get the impression that openhab itself is leaving something behind after Deinstallation, hat blocks the required ports. I got it running with the latest snapshot. Then I messed up some configuration so it didn't start anymore. I tried to reinstalled it several times now, cleaned my ds of all services I don't need and it's still not working. Sometimes it is at least running, but I can't access the webif on the given ports

**Comment by cniweb** [comment]
At the moment, unfortunately, only the HTTP port is to configure the install. We are currently working on making the other ports configurable.

**Comment by BergmDaniel** [comment]
Thanks for your great ideas. I have checked the /usr/local/etc/services.d/ Files there was no Service which used the 8443 but ones with 8080. After uninstalling this Service (UBNT Unifi Controler), i could installed the OH package whitout any problem and could also installed the Unifi Controler on a diferend Port.
Thanks to your help, now i can start with OH on my Syno!
BR

**Comment by cniweb** [comment]
I repoen it, we plan to configure all port´s at installation.

**Comment by haegar33** [comment]
So which ports are actually required during installation? 8080? How show I disable other services on my NAS if I dont know the needed port? And for a good Synology package the new application should obey the existing port configuration. Too bad for such a good SW like OpenHab not be able to be used on my NAS.

**Comment by andre2308** [comment]
Hey @haegar33,
In the latest Release you can configure the HTTP Port you want to use. Standard Ports are 8080 for HTTP an 8443 for HTTPS, in the Latest sourcecode you can chose HTTPS too. On Installation will openhab Check your chosen ports are free.

**Comment by cniweb** [comment]
no, that is not yet possible. I have to build a new release first...

**Comment by cniweb** [comment]
I released a new version withe a fix.
