### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Harald1966** [openhab/openhab-syno-spk#119]
I install the Java 8 and update to ....151 version.

DS 1815+
DSM 6.1.4-15217 Update 3

I check it with 7 and 8 but always get this message 👍 

/usr/local/bin/java Downloading source failed

Can you help

Thanks 

Harald

**Comment by cniweb** [comment]
Yesterday the new version 2.2.0 has been released. That's why the URL does not fit anymore. We are currently in the process of building a new package.

**Comment by Harald1966** [comment]
thanks

**Comment by cniweb** [comment]
You can use the new final release 2.2.0:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.2.0.010

**Comment by cniweb** [comment]
@Harald1966 Can I close this Issue?

**Comment by Harald1966** [comment]
Yes works super thanks a lot
