### ISSUE TITLE
synology update-openhab wont start

### ISSUE THREAD

**Issue by tordenfod** [openhab/openhab-syno-spk#120]
just updated ny syno to DSM 6.1.4-15217 Update 3
Now openhab (2.2.0.008) wont kick in..

solution ?

Other than reinstall :-)

**Comment by cniweb** [comment]
Yesterday the new version 2.2.0 has been released. That's why the URL does not fit anymore. We are currently in the process of building a new package.

**Comment by cniweb** [comment]
You can use the new final release 2.2.0:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.2.0.010

**Comment by cniweb** [comment]
@tordenfod Can I close this Issue?
