### ISSUE TITLE
Virgin installation of 2.2.0 - error (java) User Home Service not enabled

### ISSUE THREAD

**Issue by piejanssens** [openhab/openhab-syno-spk#121]
![image](https://user-images.githubusercontent.com/829098/34152019-6bd420c4-e4ad-11e7-94e8-326b317687f5.png)

I installed the official Java 8 pkg before installing openHAB.
I created the shared folder 'openHAB' and gave r/w permissions to 'guest' (is this necessary?).

**Comment by piejanssens** [comment]
I enabled the DSM "User's Home" option (strange requirement!) to get passed this error.
Now the OpenHAB install completed and I could start and load up OH.
There is not a single file generatesd in /public/openHAB/conf (or userdata or addons).

**Comment by piejanssens** [comment]
Is the UH_SERVICE check done only because enabling the home service would create the public share?

**Comment by cniweb** [comment]
Yes, I think the option is only for that. So if in Wizzard another option than the share folder in the user home settle, then the user home service can remain disabled.

**Comment by piejanssens** [comment]
There is nothing 'public' about openHAB config files and therefore I don't see a particular reason to want it as part of the 'Public' shared folder
Please note that enabling the user home folder on DSM6+ (at least my version) does not create the public folder, so to use the home UH_SERVICE check to assume the 'Public' share will be there makes no sense.

The best (IMO) solution for the wizard would be to let the user select the destination for the conf files and if possible create the 'conf', 'userdata' and 'addons' folders in that selected directory automatically.
So replace the radio buttons with a single input field where the user needs to enter the path to the root folder for the OH files starting with the name of a shared folder. There is already code in place to check if that folder exists. e.g. I would enter 'openHAB'. If you want it in public you could enter 'Public/openHAB'.

**Comment by cniweb** [comment]
@SchoppAx What do you think about?

**Comment by SchoppAx** [comment]
That’s an easy enhancement.

I will change the destination settings in the holidays ;-)

**Comment by acseven** [comment]
Hi,

I think this is related to this new option that we get during installation:
![scrn](https://user-images.githubusercontent.com/1176371/35644487-f602d684-06c0-11e8-8041-fe2945f66b60.png)

Just want to suggest that the setup description would make a reference to the first two being shared folders - at least I didn't figure it out for "SmartHome" at first. Something like "(share must exist..." should suffice... 

Cheers

**Comment by cniweb** [comment]
@acseven Sounds good and should be easy to implement...

**Comment by HakamSaffour** [comment]
I made a pull request to add the missing step
2. Go to Control Panel → User → Advanced → User Home and check 'Enable user home service' 
https://github.com/openhab/openhab-docs/pull/910

This issue can be closed
