### ISSUE TITLE
request: openHAB 2.3 on DSM 6.2

### ISSUE THREAD

**Issue by yphyph01** [openhab/openhab-syno-spk#129]
Hi @cniweb ,
Would be nice to have the openHAB new release 2.3 on the fresh new synology DSM package 6.2 :-)
Any idea of its availability?
Thank you 
Yann

**Comment by cniweb** [comment]
I´m work on it!

**Comment by cniweb** [comment]
@yphyph01 can you try, please:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.3.0.002

**Comment by yphyph01** [comment]
@cniweb thank you for your job.
I've tried the new release .... without success.

Here are the synopkg.log:

`2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/openHAB
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/openHAB ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/rm -rf /var/packages/openHAB
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/rm -rf /var/packages/openHAB ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mkdir -p /var/packages/openHAB
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mkdir -p /var/packages/openHAB ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/openHAB/INFO
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/openHAB/INFO ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/rm -rf /var/packages/openHAB/scripts
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/rm -rf /var/packages/openHAB/scripts ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/openHAB/scripts
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/openHAB/scripts ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/rm -rf /var/packages/openHAB/WIZARD_UIFILES
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/rm -rf /var/packages/openHAB/WIZARD_UIFILES ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/openHAB/WIZARD_UIFILES
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/openHAB/WIZARD_UIFILES ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/rm -rf /var/packages/openHAB/conf
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/rm -rf /var/packages/openHAB/conf ret=[0]
2018/05/30 11:30:41     install openHAB 2.3.0.002 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/openHAB/conf
2018/05/30 11:30:41     install openHAB 2.3.0.002 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/openHAB/conf ret=[0]
2018/05/30 11:30:42     install openHAB 2.3.0.002 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2018/05/30 11:30:42     install openHAB 2.3.0.002 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2018/05/30 11:30:42     install openHAB 2.3.0.002 successfully
2018/05/30 11:30:45     install openHAB: begin to start version 2.3.0.002
2018/05/30 11:30:45     install openHAB 2.3.0.002 Begin pre-load apparmor
2018/05/30 11:30:45     install openHAB 2.3.0.002 End pre-load apparmor ret=[0]
2018/05/30 11:30:45     install openHAB 2.3.0.002 Begin start-stop-status start
find: `/var/log/openHAB-start_stop.log': No such file or directory
su: user openhab does not exist
2018/05/30 11:30:45     install openHAB 2.3.0.002 End start-stop-status start ret=[1]
2018/05/30 11:30:46     (system) trigger openHAB 2.3.0.002 Begin start-stop-status stop
2018/05/30 11:30:46     (system) trigger openHAB 2.3.0.002 End start-stop-status stop ret=[0]
2018/05/30 11:30:46     (system) trigger openHAB 2.3.0.002 Begin unload apparmor
2018/05/30 11:30:46     (system) trigger openHAB 2.3.0.002 End unload apparmor ret=[0]
2018/05/30 11:30:47     stop openHAB: begin to stop version 2.3.0.002
2018/05/30 11:30:47     stop openHAB: stop version 2.3.0.002 successfully, result 0
2018/05/30 11:30:47     install openHAB: start version 2.3.0.002 failed, result 272
`

 and the openHAB-start_stop.log

`Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
`

Please, let me know if I could provide additional information to help your investigation :-)
Regards

**Comment by yphyph01** [comment]
and the OpenHAB_install.log file: 
`#### S T A R T  -  o p e n H A B  S P K ####
2018-05-30:11:46:18

Set instance variables...
  public:
  smarthome:
  home:
  tmp:    /volume2/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab
  backup: /volume1/@appstore/openHAB-backup-201805
done
Start preuninst...
done
#### S T A R T  -  o p e n H A B  S P K ####
2018-05-30:11:46:28

Set instance variables...
  public:
  smarthome:
  home:
  tmp:    /volume2/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab
  backup: /volume1/@appstore/openHAB-backup-201805
done
Start postuninst...
  Daemon user folder '' not found - nothing deleted
done
`

**Comment by slydlake** [comment]
Same issue here. i have the openHAB 2.2 installed
Problem is that the openHAB user will deleted (update installation) and not recreate or with errors

**Comment by cniweb** [comment]
OK, can you try a uninstall and new install (no update!)?

**Comment by yphyph01** [comment]
I've done ... Without success

⁣Envoyé par BlueMail ​

Le 30 mai 2018 à 20:34, à 20:34, "Christian Häussler" <notifications@github.com> a écrit:

**Comment by andre2308** [comment]
Hey, 
I have the same problem as slydlake and yphyph01 on DSM 6.1.7-15284.

**Comment by Snowrisk** [comment]
Same here.... (@ DSM6.2)

**Comment by HeikoB** [comment]
Me too @ DSM 6.2

**Comment by rhusername** [comment]
Thanks for all the work that’s been done.  Same here, same errors.  Unable to install 2.3.x (001 or 002).

**Comment by Cheesythebest** [comment]
Same for me. Openhab 2.3 doesn't work for me on my Syno 415+ DSM 6.2. Not with fresh install and not with update from 2.2.
After this i had install Openhab 2.2 new, this works fine!

**Comment by kaikreuzer** [comment]
@cniweb Any news on this? It seems that many people are struggling with 2.3 on DSM...

**Comment by cniweb** [comment]
You can try the new release:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.3.0.003

**Comment by yphyph01** [comment]
thank you for your job @cniweb 
It's working :-)
Regards
