### ISSUE TITLE
openHAB-2.3.0.003-syno-noarch-0.001 doesn't start

### ISSUE THREAD

**Issue by zuernc** [openhab/openhab-syno-spk#132]
- DS415+, DSM 6.1.7-15284, JAVA8 is up to date

- Installed openHAB-2.3.0.003-syno-noarch-0.001 and got the following in my log:

> [SEVERE] [org.apache.karaf.main.Main] - Could not launch framework
> java.lang.RuntimeException: Could not resolve mvn:org.eclipse.platform/org.eclipse.osgi/3.11.3
>     at org.apache.karaf.main.util.SimpleMavenResolver.resolve(SimpleMavenResolver.java:59)
>     at org.apache.karaf.main.Main.createClassLoader(Main.java:457)
>     at org.apache.karaf.main.Main.launch(Main.java:254)
>     at org.apache.karaf.main.Main.main(Main.java:179)

- openHAB-2.3.0.002-syno-noarch-0.001 not starting either (and the install deleted my openhab user)

- went back to openHAB-2.2.0.010-syno-noarch-0.001 which is working fine

Any thoughts on how I could fix this so as to use the newest version? Thx!

**Comment by richterfritz** [comment]
Same for me, all three versions not working, with the 003 version I get the same maven error :(

**Comment by SyntaxError-404** [comment]
I have exactly the same issue.

**Comment by cniweb** [comment]
@kaikreuzer What can this be?

**Comment by kaikreuzer** [comment]
No clue, sounds like some broken distro... Do I get it right that no 2.3 packaging worked so far? Or just not for certain DSMs?

**Comment by yphyph01** [comment]
@kaikreuzer the distro 2.3 is working on DSM 6.2.
validation done by several users ;-)

**Comment by zuernc** [comment]
As soon as DSM 6.2 gets available in my region I will post an update. Thanks to you all!

**Comment by fritzrichter** [comment]
worked for me now... I needed to install it to a fresh directory, which was different to my previous one "/SmartHome". It seems to work now.

**Comment by cniweb** [comment]
Yes, you must install in a fresh directory. The update is not still work at the moment.
