### ISSUE TITLE
Can't install 2.4.0.001 on DSM 6.2.1-23824 Update 4( DS 713+)

### ISSUE THREAD

**Issue by schlaubi666** [openhab/openhab-syno-spk#149]
I have never installed this package before.

I select the downloaded package from my download folder and hit the next button.

Then i get the error:

![image](https://user-images.githubusercontent.com/24993136/52749337-24a21c00-2fe9-11e9-8a4e-f92737b83282.png) ( if your german is not so good ... Port undefined is configured to be used in thes package , is used by someone else or is reserved by the system)

how to fix this ?

**Comment by schlaubi666** [comment]
sudo netstat -nlp | grep 8080
sudo netstat -nlp | grep 8443

shows no result

**Comment by slydlake** [comment]
Did you try to upload the file with chrome?

**Comment by cniweb** [comment]
I see in the background, you installed Tomcat? Witch port use this?

**Comment by schlaubi666** [comment]
No, i did not installed tomcat.

Christian Häussler <notifications@github.com> schrieb am Mo., 25. Feb.
2019, 16:06:

**Comment by bunzilein** [comment]
I have the same exact issue.
Ports 8080, 8443 and 5555 are all not in use on my DiskStation.
Tried Chrome and Safari to upload the spk.

**Comment by cniweb** [comment]
@schlaubi666 and @bunzilein I have released a new version with the fix.

**Comment by bunzilein** [comment]
Thanks Christian!
