### ISSUE TITLE
Make Port configurable

### ISSUE THREAD

**Issue by fsedarkalex** [openhab/openhab-syno-spk#15]
I needed to investigate to find out which port is used by openHAB within your SPK.
I would suggest to make it configurable during setup, that would add much of comfort and control to it.
##

**Comment by cniweb** [comment]
Hi @fsedarkalex,

this turns out unfortunately a bit difficult because when the installation process of DiskStation packages no parameters can be passed.
But if your configuration is below **/volume1/public/openhab/configurations** can be set **openhab.cfg** in here a different port.
This place is incidentally not overwritten during an update!

Thank you for your involvement!

Chris

**Comment by fsedarkalex** [comment]
well I know how to do it afterwards, sure!

I saw the UsbSerial-SPK lets you choose which drivers to install so somehow it must be possible in my opinion.

**Comment by cniweb** [comment]
OK, can you help me? Can you find a link to the source code? Than can I look... ;-)

**Comment by fsedarkalex** [comment]
https://forum.synology.com/enu/viewtopic.php?f=155&t=82843&start=420

You could talk to "jadahl" probably he can give you some information on this :)

**Comment by cniweb** [comment]
Hi @gizmocuz (jadahl?), can you help us?

**Comment by wars85** [comment]
What is the default port configured in the package? when I try to install the spk, I receive the message that the port is already in use.

**Comment by Sheriff-Donnerknall** [comment]
Default port ist 8080.

**Comment by gooxbe** [comment]
Hello,

It would be great as my OH2 don't start either and my port 8080 is busy.

I checked on https://community.openhab.org/t/no-access-to-openhab2-via-port-8080/6080 and https://community.openhab.org/t/changing-port-number-on-openhab-2-0/2300

So I tried to change port in `start_runtime.sh`, `start_runtime_debug.sh` and `/runtime/bin/setenv`. I even added `env` variable and finally did an `export` in despair.
As I was ready to hange myself, I also added `OPENHAB_HTTP_PORT=8081` & `OPENHAB_HTTPS_PORT=8445` to `start_runtime.sh` and `start_runtime_debug.sh`

When starting it on my synology, it starts on 8080 anyway. Any clues? Should I try to build it on my syno?

**Here are some logs:**

`uname -a: Linux GooxStation 2.6.32.12 #8451 SMP Wed Nov 9 13:44:31 CST 2016 ppc GNU/Linux synology_qoriq_213+`

In my logs I have:
`java.net.BindException: Address already in use`

```
sudo ./start_debug.sh
Launching the openHAB runtime...
Java HotSpot(TM) Embedded Client VM warning: G1 GC is disabled in this release.
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
/volume1/@appstore/openHAB2/runtime/bin/karaf: line 366:  8788 Aborted                 (core dumped) $KARAF_EXEC "$JAVA" $JAVA_OPTS -Djava.endorsed.dirs="${JAVA_ENDORSED_DIRS}" -Djava.ext.dirs="${JAVA_EXT_DIRS}" -Dkaraf.instances="${KARAF_HOME}/instances" -Dkaraf.home="$KARAF_HOME" -Dkaraf.base="$KARAF_BASE" -Dkaraf.data="$KARAF_DATA" -Dkaraf.etc="$KARAF_ETC" -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir="$KARAF_DATA/tmp" -Djava.util.logging.config.file="$KARAF_BASE/etc/java.util.logging.properties" $KARAF_OPTS $OPTS -classpath "$CLASSPATH" $MAIN "$@"
```

```
sudo ./start_debug_runtime.sh
find: `server': No such file or directory
Launching the openHAB runtime in debug mode...
Error: Unable to access jarfile 5555
PID is:
```

**Comment by cniweb** [comment]
Hello @gooxbe,

you must already edit line 10 in the INFO file:
https://github.com/openhab/openhab-syno-spk/blob/2.0-SNAPSHOT-DSM6/INFO#L10

And the folder structure was updated!
See #37 

Christian

**Comment by gooxbe** [comment]
Great, I should try this as you might have seen my other post, can't get the spk installation to work...
Thanks for your help!

**Comment by SchoppAx** [comment]
Done!

Please checkout the new pre-release: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.007-SNAPSHOT
