### ISSUE TITLE
snapshot support for openhab 2.5

### ISSUE THREAD

**Issue by Timtam** [openhab/openhab-syno-spk#158]
It would be nice to have e.g. a branch for already available OH 2.5 snapshots to test new features on a Synology NAS without fiddling with the manual installation. This branch could be updated to install the latest stable 2.5 version as soon as it gets released.

**Comment by cniweb** [comment]
I try to take care of it the next few days.

**Comment by Timtam** [comment]
Thanks for that :). Any progress on that? I just thought that having a release which will always pull the very latest snapshot might be even more future proof here and probably kinda helpful for bleeding edge testers.

**Comment by X015** [comment]
Any news on the 2.5 SNAPSHOT?
Realy looking forward to it!

Thanks!

**Comment by ddnl** [comment]
looking forward to the 2.5 snapshot for synolgy

**Comment by cniweb** [comment]
I'll try to do it next week...

**Comment by piejanssens** [comment]
Looking more forward to 2.5 final which came out yesterday 😄

**Comment by cniweb** [comment]
You can test it:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.5.0.000

**Comment by piejanssens** [comment]
> You can test it:
> https://github.com/openhab/openhab-syno-spk/releases/tag/2.5.0.000

Didn't go too well. In the UI it says "Failed to run package service."
I tried to run it via the script. Noticed the following permissions:

```
-rw-rw-r-- 1 root root 20199 Dec 16 18:03 installer.sh
-rwx------ 1 root root    52 Dec 16 18:03 postinst
-rwx------ 1 root root    52 Dec 16 18:03 postuninst
-rwx------ 1 root root    52 Dec 16 18:03 postupgrade
-rwx------ 1 root root    76 Dec 16 18:03 preinst
-rwx------ 1 root root    52 Dec 16 18:03 preuninst
-rwx------ 1 root root    76 Dec 16 18:03 preupgrade
-rw-rw-r-- 1 root root  6060 Dec 16 18:03 restore
-rwx------ 1 root root    49 Dec 16 18:03 start-stop-status
-rw-rw-r-- 1 root root  3790 Dec 16 18:03 start-stop-status.sh
```

Then did a chmod -R 755 on the /var/packages/openHAB dir.

```
pieter@DISKSTATION:/var/log$ cat openHAB-install.log 
#### S T A R T  -  o p e n H A B  S P K ####
2019-12-16:19:35:44

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  TMPFS:     false
  Z-Wave:    true
  port:    8080
  port:    8443
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB
  backup: /volume1/@appstore/openHAB-backup-201912
done
User that exec the Installation
root
Start preuninst...
done
#### S T A R T  -  o p e n H A B  S P K ####
2019-12-16:19:35:56

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  TMPFS:     false
  Z-Wave:    true
  port:    8080
  port:    8443
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB
  backup: /volume1/@appstore/openHAB-backup-201912
done
User that exec the Installation
root
Start postuninst...
  Daemon user folder '/var/services/homes/openhab' not found - nothing deleted
done
```

```
pieter@DISKSTATION:/var/log$ cat openHAB-start_stop.log 
Stop service.
  Stopping openHAB ...
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  wait_for_status: 1
  stop_daemon: kill service
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
```

**Comment by Hoffi96** [comment]
got exactly the same error. Just installed 2.5 over my existing 2.4 installation

**Comment by cniweb** [comment]
OK, I see why. New release is in progress.

**Comment by cniweb** [comment]
Can you try again:
https://github.com/openhab/openhab-syno-spk/releases/download/2.5.0.000/openHAB-2.5.0.000-syno-noarch-0.001.spk

**Comment by piejanssens** [comment]
![image](https://user-images.githubusercontent.com/829098/71005326-c439aa80-20e3-11ea-8f73-7d5854d927e6.png)

I can't access the log atm. Will do in a couple of hrs.

**Comment by cniweb** [comment]
You must uninstall first and than install new (backup your files first).

**Comment by Hoffi96** [comment]
same error as described above

**Comment by mbremer99** [comment]
Installation worked for me - did uninstall of failed package this morning and now installed new spk.
This is the log from the sucessfull install:

`#### S T A R T  -  o p e n H A B  S P K ####
2019-12-17:20:40:47

Set instance variables...
  public:    false
  smarthome: false
  home:      true
  TMPFS:     false
  Z-Wave:    false
  port:    8080
  port:    8443
  tmp:    /volume1/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab
  backup: -backup-201912
done
User that exec the Installation
root
Start preinst...
  Found java executable in PATH
  Java version 1.8.0_231
  Version is more than 1.8
  The User Home service is enabled. UH_SERVICE=yes
  The shared folder '/var/services/homes' exists.
  Get new version
  Processing openhab-2.5.0.zip
done
#### S T A R T  -  o p e n H A B  S P K ####
2019-12-17:20:40:54

Set instance variables...
  public:    false
  smarthome: false
  home:      true
  TMPFS:     false
  Z-Wave:    false
  port:    8080
  port:    8443
  tmp:    /volume1/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab
  backup: /volume1/@appstore/openHAB-backup-201912
done
User that exec the Installation
root
Start postinst...
  Create 'openhab' daemon user
  Install new version
    Extract openhab-2.5.0.zip
    Move files to /volume1/@appstore/openHAB
No TMPFS Install needed
  Create conf/addon/userdata folders for home dir
    Move conf to /var/services/homes/openhab/conf and create conf link
    Move addons to /var/services/homes/openhab/addons and create addons link
    Move userdata to /var/services/homes/openhab/userdata and create userdata link
  Fix permissions
done
No Z-Wave Wanted`
