### ISSUE TITLE
No user interfaces installed

### ISSUE THREAD

**Issue by michabbb** [openhab/openhab-syno-spk#159]
hi, i installed the package and accidentally clicked on the wrong link after the first start.
now i am stuck with the message "No user interfaces installed." 
what can i do to install one?

thanks!

**Comment by cniweb** [comment]
Can you add a screen-shot?

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/71086208-90b95780-2199-11ea-8aa2-6c53d6bb7b8f.png)

**Comment by cniweb** [comment]
This is not a problem of this package. openHAB2 downloads everything when you start it, including the GUI. It usually takes a while.

**Comment by michabbb** [comment]
i am totally new to openHAB, sorry if this is the wrong place. can you give me some advise anyway? i have absolutly no idea how i can work with openHAB right now because the is no GUI.

**Comment by cniweb** [comment]
At the first start this should actually come:
https://www.openhab.org/docs/tutorial/1sttimesetup.html
Maybe this helps:
https://community.openhab.org/t/solved-ui-missing/45952/3

**Comment by michabbb** [comment]
thanks for your help, i guess the only thing that would help is a new fresh re-install, but currently i am no longer in openhab, maybe another time, thanks!
