### ISSUE TITLE
Upgrade from 2.4.0.002 to 2.5.0.000

### ISSUE THREAD

**Issue by poval82** [openhab/openhab-syno-spk#160]
Hello,
Is there automatic mechanism to upgrade from  2.4.0.002 to 2.5.0.000 ?

**Comment by cniweb** [comment]
Unfortunately not at the moment. It is best to save the configuration beforehand.

**Comment by poval82** [comment]
Do you mean backup and restore scripts in bin folder ?

**Comment by cniweb** [comment]
No manual copy in a other folder

**Comment by daniedj** [comment]
> Unfortunately not at the moment. It is best to save the configuration beforehand.

I'm not able to find the instructions for updating from 2.4 : I've to remove 2.4 and install 2.5?

**Comment by TheRealMoeder** [comment]
Yes you have to backup your configuration, uninstall 2.4 and reinstall 2.5. For me, completely moving over conf and userdata was troublesome, so I did the following from Synology ssh console:
1.) Stop openhab 2.4 service
2.) Backup configuration files and persistence
sudo cp -ar /youropenhabfolder/conf /yourbackupfolder
sudo cp -ar /youropenhabfolder/userdata/jsondb /yourbackupfolder/userdata/jsondb
sudo cp -ar /youropenhabfolder/userdata/persistence /yourbackupfolder/userdata/persistence
3.) Uninstall openhab 2.4 package
4.) Delete remaining files in /youropenhabfolder and recreate addons, conf and userdata folders
5.) Install openhab 2.5 package
6.) open openhab UI to finalize setup and install the needed Addons for your configuration from paperui
7.) stop openhab 2.5 package
8.) sudo cp -ar the files you backed up in step 2 back to /yourbackupfolder
9.) Fix file ownership for the backed up files as installing the new openhab package will create openhab user with a different uid:
sudo chown  -hR openhab /youropenhabfolder/*
10.) restart openhab 2.5 package
11.) with some patience all should be up and running again.

**Comment by daniedj** [comment]
> Yes you have to backup your configuration, uninstall 2.4 and reinstall 2.5. For me, completely moving over conf and userdata was troublesome, so I did the following from Synology ssh console:
> 
> 1.) Stop openhab 2.4 service
> 2.) Backup configuration files and persistence:
> sudo cp -ar /youropenhabfolder/conf /yourbackupfolder/conf
> sudo cp -ar /youropenhabfolder/userdata/jsondb /yourbackupfolder/userdata/jsondb
> sudo cp -ar /youropenhabfolder/userdata/persistence /yourbackupfolder/userdata/persistence
> 3.) Uninstall openhab 2.4 package
> 4.) Delete remaining files in /youropenhabfolder and recreate addons, conf and userdata folders
> 5.) Install openhab 2.5 package
> 6.) open openhab UI to finalize setup and install the needed Addons for your configuration from paperui
> 7.) stop openhab 2.5 package
> 8.) sudo cp -ar the files you backed up in step 2 back to /youropenhabfolder
> 9.) Fix file ownership for the backed up files as installing the new openhab package will create openhab user with a different uid:
> sudo chown -hR openhab /youropenhabfolder/*
> 10.) restart openhab 2.5 package
> 11.) with some patience all should be up and running again.

thank you! I'll try
