### ISSUE TITLE
Simple guide how to upgrade (always the latest version)

### ISSUE THREAD

**Issue by rokrodic** [openhab/openhab-syno-spk#162]
Hi.
This is not an issue, but a simple video guide how to upgrade and always have the latest OpenHAB version on your Synology NAS:
[https://youtu.be/-ArEEJRXVU8](https://youtu.be/-ArEEJRXVU8)

BTW, inbetween the versions have advanced, but the guide is very simple. All you have to do is to find the latest link and ZIP file for the OpenHAB.

Rok Rodic
[https://www.rodic.si](https://www.rodic.si)
[https://www.youtube.com/channel/UCIOIhhPirDJH8LB0azJmd8w](https://www.youtube.com/channel/UCIOIhhPirDJH8LB0azJmd8w)

**Comment by cniweb** [comment]
Thank you @rokrodic, would you add that to the [README.md](https://github.com/openhab/openhab-syno-spk/blob/master/README.md)?
