### ISSUE TITLE
openHAB 3 installation does not work.

### ISSUE THREAD

**Issue by ingof** [openhab/openhab-syno-spk#163]
I tried to install the openHAB 3.0 beta SPK.
The installation tries to create the user openhab and delivers user and password for the user. The command is line 177 in install.sh.

The user creation is failing. In my oppinion is the reason a missing password.
${DAEMON_PASS} is probaply not defined.

I could not find the set of ${DAEMON_PASS} in OH2.4 but this installs withour problems.
Where is the daemon-password set??

**Comment by ingof** [comment]
this is the content of /var/log/openHAB-start_stop.log after manual creating the user "openhab" with password "openhab":

> Start service
>   call start.sh.
>   FAILED (su)
> Stop service.
>   openHAB is not running
> done.
> Start service
>   call start.sh.
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   wait_for_status: 0
>   PID file created.
> done.

**Comment by manudar** [comment]
Hi, neither 2.5 nor 3.0 packages work for me (I and doubt for anybody) because the permisions of the sh scripts in it are wrong. Take a look to this post
https://community.openhab.org/t/solved-synology-2-5-spk-install-problems/87775/19
I explain it there and I provide the fixed packages. I tested the 2.5, but not the 3.0.
