### ISSUE TITLE
Location and editing of conf files 

### ISSUE THREAD

**Issue by keepsmilyn** [openhab/openhab-syno-spk#164]
Ive successfully installed openHAB on my synology, however how do I create and edit files within the conf sub folders? 

I was able to do this easily when installed on a windows test environment previously. 

openHAB seems to be running from /volume1/@appstore/openHAB instead of '/SmartHome/openHAB' shared folder as created and selected on install. :-S How can I easily access where it installed? Is the only option via SSH / Telnet??

**Comment by cniweb** [comment]
During installation you can choose where the user folder should be.
The **/volume1/public** should actually already exist and be available as a network share.
For example, you can choose this folder during installation:
`/volume1/public/openHAB`

**Comment by keepsmilyn** [comment]
Actually, no in our case we didnt have a 'public' folder so it wont ever save there. Even when choosing one of the other options it still defaulted to /volume1/@appstore/openHAB. 

In the end we have left it there and ran 'SUDO mount -o /EXISTING-LOCATION /MAPPED-LOCATION/ to enable access to the files elsewhere without SSH access.

**Comment by cniweb** [comment]
OK, then can we close the issue?
