### ISSUE TITLE
DSM 6 and OpenHAB-2.0.0-beta2-syno-noarch-0.001.spk

### ISSUE THREAD

**Issue by igorrobertifoc** [openhab/openhab-syno-spk#17]
Hi,
great thing this packet. The installation finish good.
But the service doesn't start and with console it give me this error: 

ash-4.3# sh start_runtime.sh
find: `server': No such file or directory
Launching the openHAB runtime...
ash-4.3# Error: Unable to access jarfile 5555

Do you have an idea for starting the app?

**Comment by cniweb** [comment]
Hi @igorrobertifoc,

under what firmware your package runs?
 We have 2 branches, for <= 5.2 and 6.0...

What a DS model you use?

Thank you for your involvement!

Chris

**Comment by igorrobertifoc** [comment]
Hello, 
Is it impossible to run 2.0Beta on DSM 6?

Thank you very much

**Comment by gittela** [comment]
It's a bug with the installer. 7zip has replaced unzip with a slightly different syntax. I've added a suggested fix to installer.sh.

**Comment by cniweb** [comment]
Sorry, but the openhab:2.0-beta1 branch is only for DSM 4 or 5!
A new branch for openhab 2.0 and DSM 6 is still needed...
In the DSM-6.0-beta branch is 7zip already implemented:
https://github.com/openhab/openhab-syno-spk/blob/DSM-6.0-beta/scripts/installer.sh#L79

**Comment by cniweb** [comment]
I have released a new OpenHab 2.0 DSM 6 release:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta2-DSM6-RC
Try it, please!

**Comment by gittela** [comment]
I tried the beta and it installs fine, but it will not run. I can start it from by running start.sh in cli, but not from gui. It simply won't start with no error message. If I run start_runtime.sh from cli I get this:
find: `server': No such file or directory
Launching the openHAB runtime...
Error: Unable to access jarfile 5555

From what I can see it tries to locate the eclipse binaries with this:
cp=$(find $eclipsehome -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -n 1);

This does not return a result when run outside as:
find $eclipsehome -name "org.eclipse.equinox.launcher_*.jar"

Any ideas?

**Comment by cniweb** [comment]
Hi @gittela,

another user had the same problem and could solve it by he had reinstalled Java.
Try it once, I hope it helps.

Chris

**Comment by gittela** [comment]
Unfortunately that did not help. Same error. It must be noted that I'm running this on a PPC-based Synology, the DS413 and from what I can tell the latest available jre8 is 1.8.0_06. Seems that it is not being updated anymore.

If I do this on my Ubuntumachine:
howard@openhab:/opt$ locate org.eclipse.equinox.launcher | sort | tail -n 1
I get this:
/usr/lib/jvm/java-8-oracle/lib/missioncontrol/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar

This jar is not present in the OpenHAB/runtime/karaf/system/de/maggu2810/p2redist/ folder

Should it have been downloaded during install? I can always try to copy it and see...

**Comment by cniweb** [comment]
Can you even look to see if the server directory actually exists?

**Comment by gittela** [comment]
Yes it does. It runs if I use **start.sh**, it's the **start_runtime.sh** script that fails.

**Comment by cniweb** [comment]
If you manually start the **start_runtime.sh** script, what is to come exactly for errors?

**Comment by mro10** [comment]
Hi @cniweb 

not sure if that helps, but the output of start_runtime.sh is:

find: `server': No such file or directory
Launching the openHAB runtime...
Error: Unable to access jarful 5555

I´m not sure, but 
eclipsehome="server"
seems to expect a folder "server" inside the openhab folder which does´t exist.

**Comment by Veance** [comment]
Hi,

> Launching the openHAB runtime...
> Error: Unable to access jarful 5555

Have a look at /usr/local/etc/services.d/
There might be an old "OpenHAB.sc" that reserve 5555, 8081, 8443 ports, delete it and try to start openhab. 

Regards

**Comment by cniweb** [comment]
Can you look this:
> netstat -an | grep 5555

Chris

**Comment by nikolayNNN** [comment]
Hello,

I have the same problem: Synology DS 214 play
DSM 6.0-7321 Update 2
Java version 1.8.0_60

ash-4.3# ./start_runtime.sh 
find: `server': No such file or directory
Launching the openHAB runtime...
Error: Unable to access jarfile 5555

netstat -an | grep 5555

shows nothing, I'm sure that this port is not occupied.

/usr/local/etc/services.d/* files does not contain anything about this port. I have a fresh installation of openHAB

By doing:
ls runtime/karaf/system/de/maggu2810/p2redist/
I see  no org.eclipse.equinox.launcher directory. Is this a part of OpenHab package or it should be in  Java?

**Comment by dmihhailov** [comment]
I also have the same issue.
Running DSM 6 update 2. Installed Java 8, OpenHAB2 2.0.0-beta2-DSM6-RC

After some searching around and trying things I did also came to conclusion that it fails due to not be able to locate find -name "org.eclipse.equinox.launcher_.jar"
This row seems fishy eclipsehome="server" as there is no such folder

**Comment by igorrobertifoc** [comment]
Hello dmihhailov,
can you explain? Where did you download equinox?

**Comment by igorrobertifoc** [comment]
Ok,
if I use start.sh instead of start_runtime.sh then it work.
How to use this command from the UI of synology

**Comment by siberski** [comment]
seems that `start_runtime.sh` has not been adapted to OpenHAB2. It should probably start `runtime/karaf/bin/server`, but still tries to find equinox.

**Comment by crystollic** [comment]
A while ago I changed start_runtime.sh as below and it stops/starts from the Sinology UI. I fiddled with other stuff too and was't sure what else I changed to get it working. 

echo Launching the openHAB runtime...
# PROGRAM="java -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=${HTTP_PORT} -Djetty.port.ssl=${HTTPS_PORT} -Djetty.home=. -Dlogback.configurationFile=configurations/logback.xml -Dfelix.fileinstall.dir=addons -Djava.library.path=lib -Djava.security.auth.login.config=./etc/login.conf -Dorg.quartz.properties=./etc/quartz.properties -Djava.awt.headless=true -jar $cp $* -console ${TELNET_PORT}"
# $PROGRAM > logs/openhab.stdout &
DIRNAME=`dirname "$0"`
${DIRNAME}/runtime/karaf/bin/karaf "${@}" > logs/openhab.stdout &

**Comment by cniweb** [comment]
OK, I think, we must use `start.sh`.
Can anyone try it, please?
Then I change the command in start-stop-status.sh script.

Thanks,
Chris

**Comment by siberski** [comment]
What crystolic wrote looks good. I'll try during the next few days. Not sure if we can directly use `start.sh`, because that starts the OpenHAB terminal. I'm new to OpenHAB, but assume that there is some 'headless' mode (i.e., without input options). Also, not sure how to stop OpenHAB when starting it with `start.sh`.

**Comment by igorrobertifoc** [comment]
If you close the ssh terminal you terminate openhab if started on command
line. I think if you link this command to synology all will work (hope so )

Bye and thanks
Il 03/Giu/2016 21:13, "Wolf Siberski" <notifications@github.com> ha scritto:

**Comment by cniweb** [comment]
OK, I changed it in the start-stop-status.sh script in the next release!

**Comment by cniweb** [comment]
Can you try [Release 2.0.0-beta3-DSM6](https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6), please?
And it´s OK, then I can close this Issue?

**Comment by cniweb** [comment]
Hi @igorrobertifoc,

I released a new Package:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6

Try please and give me feedback, then I can close this Issue.

Thanks

**Comment by igorrobertifoc** [comment]
Hi, is changed only the port. But the system don't work very well

**Comment by cniweb** [comment]
Hi @igorrobertifoc,

this project only support the installation or openHAB an a Sanology Diskstation.
What works "very well" exactly?

Thanks for your feedback,
Chris

**Comment by igorrobertifoc** [comment]
Hello,
i'm sorry for the last short reply and I tank you for your work.
the problem is it very slow on 216play and all servicies are not up. After 15 minutes of start, the start page doesn't show all options. I don t know what happen, If there is a log file I can send to you.

Tanks

**Comment by cniweb** [comment]
Hi @igorrobertifoc,

I think you must de install the package complete and re install it.
A log file can you found in `/volume1/@appstore/OpenHAB/logs/`

Chris

**Comment by cniweb** [comment]
Hi,

we fix the logfile path: #28
and update to 2.0-SNAPSHOT release of OpenHAB2.

Chris
