### ISSUE TITLE
"Invalid file format" for 1.8.2-DSM6-RC

### ISSUE THREAD

**Issue by krzychb** [openhab/openhab-syno-spk#18]
My DiskStation got updated to DSM 6.0 and I found previously installed openHAB package 1.7.1 "stopped" in Package Center. Therefore I decided to upgrade it to release OpenHAB-1.8.2-DSM6-RC-syno-noarch-0.001.spk. 

Unfortunately I got message as below:
![capture](https://cloud.githubusercontent.com/assets/12953787/14075054/3007dc02-f4d6-11e5-9c2f-f3eaf58b289b.PNG)

Model name: DS414 
CPU: MARVELL Armada XP MV78230 
DSM version: DSM 6.0-7321 
Java: 1.8.0_077

I have also tried OpenHAB-1.8.1-DSM6-beta-syno-noarch-0.001.spk. It installs without problems but does not start. Attempting to "Run" it from Package Center does not work - it is shown as "stopped". There are no messages in "View Log".

How can I troubleshoot this issue?

Krzysztof

**Comment by cniweb** [comment]
Hi @krzychb,

I update the Release-SPK-File, try it, please:
https://github.com/openhab/openhab-syno-spk/releases/tag/1.8.2-DSM6-RC

Chris

**Comment by krzychb** [comment]
Hi @cniweb,

Thank you for quckly fixing release 1.8.2-DSM6-RC. The error "Invalid file format" is gone :+1:
I am still unable to start this package like reported above for OpenHAB-1.8.1-DSM6-beta-syno-noarch-0.001.spk but I will open separate issue for that.


Krzysztof
