### ISSUE TITLE
Bintray isn't available anymore

### ISSUE THREAD

**Issue by sergeyastakhov** [openhab/openhab-syno-spk#187]
Installer uses Bintray repository for downloading Openhab files.
Unfortunately, this server does not work any more: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Alternatively, you can try using the server https://openhab.jfrog.io/artifactory/libs-release/, at the moment there are modules for version 3.0.2

**Comment by sergeyastakhov** [comment]
Actually, it is enough to replace this line in the "scripts/intaller.sh" file:

```
#BASE_PATH='https://dl.bintray.com/openhab/mvn/org/openhab/distro/openhab'
BASE_PATH='https://openhab.jfrog.io/artifactory/libs-release/org/openhab/distro/openhab/'
```

**Comment by morthimor** [comment]
Was this enough to successfully install and run package? I did change line (actually it shouldn't have slash on end), but still installing wasn't successful until I manually downloaded openhab_3.0.2.zip file to @tmp folder. But even then it is not starting. What am I missing?

**Comment by sergeyastakhov** [comment]
I managed to successfully install the SPK file with this modification through a regular installation via the GUI and for 2 weeks now the openhab server has been working normally.
Do not forget that the OpenHub 3.0 server needs Java version 11 only and no other to work.

**Comment by dirkpollmann** [comment]
I am an new user (nothing chached) and I have to use 2.5.2 (just Java 8 support for my synology) installation will not work:

Start preinst...
  Found java executable in PATH
  Java version 1.8.0_275
  Version is more than 1.8
  The User Home service is enabled. UH_SERVICE=yes
  The shared folder '/var/services/homes' exists.
  Get new version
  Processing openhab-2.5.2.zip
  ERROR:
  There was a problem downloading openhab-2.5.2.zip from the download link:
  'https://bintray.com/openhab/mvn/download_file?file_path=org/openhab/distro/openhab/2.5.2/openhab-2.5.2.zip'
  Alternatively, download this file manually and place it in the '/var/services/homes' shared folder and start installation again.

need some help.
