### ISSUE TITLE
Synology DS213+ and OpenHab 2.0.0.002-beta2 not running 

### ISSUE THREAD

**Issue by erkobg** [openhab/openhab-syno-spk#21]
Hello,
First I installed JAVA SE Embedded 8 (Version 1.8.0_6-0034)
Then I installed manually 2.0.0-beta2-DSM6-RC from https://github.com/openhab/openhab-syno-spk/releases

Went to SSH and created both /volume1/public/OpenHAB2/addons and /volume1/public/OpenHAB2/conf ( I tried even with /volume1/public/OpenHAB2/configurations) .
gave permissions to these folders to openhab:users

Then from Package Center => Action => Run

But always the Status remains Stopped

I don't know what I am not doing as expected and what I have to do...

Any advice?

**Comment by erkobg** [comment]
When I run **sudo sh start_runtime.sh
**
I receive : 

**Launching the openHAB runtime...
Error: Unable to access jarfile 5555**

**Comment by pedeho** [comment]
Hello erkobg
Having the same problem on my DS212j. Replaced 1.8 with 2.0.0-beta2-DSM6-RC. Could not start from package manager but could start with start_runtime.sh. Tried to reinstall the RC but ended up with not able to run it at all.
Wonder if DS212j and DS213+ have something missing since it seems to run on some other stations

**Comment by cniweb** [comment]
Hi @pedeho,

can please look at your, if the port is not already in use 5555?
`netstat -an | grep 5555`

Chris

**Comment by bytedealer** [comment]
Hi,

same problem: DSM 6, openhab 2, same message as @erkobg.

No port in use after executing netstat (as above mentioned).

**Comment by bytedealer** [comment]
Ok, some more info.

I also get the error:
find: `server': No such file or directory

Call coming from start_runtime.sh: `cp=$(find $eclipsehome -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -n 1);`

The call coming from start.sh is okay: `exec "${DIRNAME}/runtime/karaf/bin/karaf" "${@}"`

So my assumption is that the call from start_runtime.sh does not find any org.eclipse.equinox.launcher_*.jar
Is there a library like this anymore?

**Comment by igorrobertifoc** [comment]
Yes, if I use start.sh all is working

**Comment by cniweb** [comment]
OK, thanks. I change it in the `start-stop-status.sh` script in the next release!

**Comment by cniweb** [comment]
Hi @erkobg, 

can you try `/volume1/@appstore/OpenHAB/start.sh`, too?

Chris

**Comment by erkobg** [comment]
Hello,
thanks for the updates.
I  downloaded the latest release and manually installed.
Then run first via package manager and then via SSH- always same result:


`2016-06-08 20:54:36.562 [WARN ] [.u.component.AbstractLifeCycle] - FAILED org.eclipse.jetty.server.Server@6af6d: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_06]
	at sun.nio.ch.Net.bind(Net.java:414) ~[na:1.8.0_06]
	at sun.nio.ch.Net.bind(Net.java:406) ~[na:1.8.0_06]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214) ~[na:1.8.0_06]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_06]
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182) ~[org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311) ~[org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	.......
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
2016-06-08 20:54:37.716 [WARN ] [.i.s.JettyServerServiceTracker] - 
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_06]
	at sun.nio.ch.Net.bind(Net.java:414) ~[na:1.8.0_06]
	at sun.nio.ch.Net.bind(Net.java:406) ~[na:1.8.0_06]
	.......
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
2016-06-08 20:54:38.720 [WARN ] [o.config.core.ConfigDispatcher] - Main openHAB configuration file 'configurations/openhab.cfg' does not exist.
2016-06-08 20:54:38.766 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.8.3).
2016-06-08 20:54:42.938 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2016-06-08 20:54:43.099 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
 
`






I am not sure which port is already reserved, but looking with "sudo netstat -tulpn | grep 80" 
shows that 8081 is not taken yet.
 How I can change the port?

**Comment by cniweb** [comment]
Can you try [Release 2.0.0-beta3-DSM6](https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6), please?
And it´s OK, then I can close this Issue?

**Comment by erkobg** [comment]
Installed the beta - status is running - but strange thing it was saying that service is running on port 8082 
accessing the URL http://myip:8082/openhab.app - says site can't be reached

Any idea why?

**Comment by cniweb** [comment]
Try Port 8081, please?

**Comment by erkobg** [comment]
Already did : This site can’t be reached

**Comment by cniweb** [comment]
OK 8080 ?
https://github.com/openhab/openhab-distro/blob/4c94da3f45b5ca414bbe49da23a6ac81b761f84f/distributions/distribution-resources/src/main/resources/bin/setenv#L57

**Comment by erkobg** [comment]
Yes it was 8080
was redirected to : 
http://myip:8080/start/index
which gave me Welcome to openHAB 2.0

**Comment by cniweb** [comment]
OK, I is a Environment variables OPENHAB_HTTP_PORT.
It is not set, then 8080 is default!
I change the Port it in the INFO file from package, OK?

**Comment by erkobg** [comment]
Yes - I think default to 8081 will be better... ( old one was like this by default)

**Comment by cniweb** [comment]
I change the Port in the INFO file from package to 8080, this is default!

I Open a another Issue for a Port definition in the Package Admin UI.

**Comment by cniweb** [comment]
Hi @erkobg,

I released a new Package:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6

Try please and give me feedback, then I can close this Issue.

Thanks

**Comment by erkobg** [comment]
Hello @cniweb,
downloaded and installed :
- it installed without any issues
- status in running
- info link for URL showing http://myip:8080/start/index
- after waiting some time (> 2mins) - url showed "Welcome to openHAB 2.0"



Cheers!

**Comment by cniweb** [comment]
Thanks

**Comment by dikkedimi** [comment]
I installed 2.0.0-beta3.spk on a DS411j and I'm also getting the "Site can't be reached" error. Already tried starting using ./start.sh to no avail, it still says site unreachable. netstat does not indicate port 8080 in use as far as I can tell.

**Comment by dikkedimi** [comment]
after running sudo ./start.sh, the server started up. It was still giving the "Site can't be reached error". After that I ran it again through the package center interface, and now the error has changed to a 404, as is visible in this image
![this](https://cloud.githubusercontent.com/assets/4985685/22410793/ef70a250-e69c-11e6-9cc6-28803d4e1dee.png)
