### ISSUE TITLE
Unable to install OpenHAB-1.8.2 on Diskstation with DSM 5.2-5664 Update 8

### ISSUE THREAD

**Issue by db1mso** [openhab/openhab-syno-spk#23]
The manual install of OpenHAB-1.8.2-syno-noarch-0.001.spk on a DS111 with DSM 5.2-5664 Update 8 gives me the following Error:

"OpenHAB" konnte nicht installiert werden. (unable to install)
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.
There was a problem downloading distribution-1.8.2-runtime.zip from the official download link, 
which was "https://bintray.com/artifact/download/openhab/bin/distribution-1.8.2-runtime.zip" 
Alternatively, you may download this file manually and place it in the 'public' shared folder. 

After a manually Download - the File distribution-1.8.2-runtime.zip already exist in the 'public' shared folder, but the error was the same.

From /var/log/messages:
entry.cgi_SYNO.Core.Package.Installation[1].install[13756]: pkginstall.cpp:405 Failed to run preinst script for OpenHAB, [1]

Hope that help
Thanks
##

**Comment by cniweb** [comment]
Hi @db1mso,

has your DS111 an Internet access?
It could also be that possibly the Hoster Bintray was unavailable...

Chris

**Comment by db1mso** [comment]
Yes, i already downloaded the zip File manualy via ssh with wget. In case of an Download Error: the zip File in public Folder should be used. 
Can i get more Infos from the installer? 
-- 
Olli

**Comment by cniweb** [comment]
Hi @db1mso,

I released a new Package:
https://github.com/openhab/openhab-syno-spk/releases/tag/1.8.3

Deinstall the old Package, please.
Try please and give me feedback, then I can close this Issue.

Thanks

**Comment by db1mso** [comment]
Hi @cniweb,

After a complete deinstall and reboot -the install worked just fine.
Thank you very much.

Keep up the good work.
