### ISSUE TITLE
Collecting working/non-working devices in a list

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-syno-spk#29]
Just playing with the idea to buy a NAS for my SmartHome setup.

Would be great if you could collect working devices in a list. With comments on their performance.

Thanks!
##

**Comment by cniweb** [comment]
@thopiekar I think, this is a good idea.
@kaikreuzer If this list in the documentation or appear in wiki from openHAB project?

**Comment by cniweb** [comment]
I updated the documentation.

Please complete the list accordingly, or write me your working models.

Thank you!

Chris

**Comment by isigmund** [comment]
I will test this on my DS1515+ in a virtual DSM environment. I will let you know my results/findings

**Comment by cniweb** [comment]
@isigmund Thanks for testing!

**Comment by ViktorShch** [comment]
DS414DSM 6.0.2-8451 Update 7
i tried to install [OpenHAB-2.0.0.008-SNAPSHOT-DSM6-syno-noarch-0.001](https://github.com/openhab/openhab-syno-spk/releases/download/2.0.0.008-SNAPSHOT-DSM6/OpenHAB-2.0.0.008-SNAPSHOT-DSM6-syno-noarch-0.001.spk)

Error:
> There was a problem downloading openhab-offline-2.0.0-snapshot.zip from the official downloading link ...

Shared folder 'Public' exist.
I tried to [openhab-2.0.0-SNAPSHOT.zip](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-2.0.0-SNAPSHOT.zip) file in 'Public' without result

**Comment by cniweb** [comment]
The download problem is known and will be fixed!

**Comment by aurelio1** [comment]
I am using OH2 on a DS213 for months now. It normally takes about 30% CPU, and it starts taking 100% after about two days. But that is probably related to Java or some binding, not to the DS.

**Comment by cniweb** [comment]
@aurelio1 Have you the last version of Java 8 installed?

**Comment by dikkedimi** [comment]
as of now it's not running on my DS411j. Well, it's running, but site cannot be reached, so it's useless so far :D

**Comment by aurelio1** [comment]
cniweb: no, I have 1.8.0_101-0041. DSM offers me to update to 121_0043 but will do so once I find the time to get it at oracle.com.

**Comment by cniweb** [comment]
We now have a package that runs under all DiskStation versions.
