### ISSUE TITLE
Worrying about symlinking

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-syno-spk#31]
Just found something strange in the installer.sh:
https://github.com/openhab/openhab-syno-spk/blob/2.0-beta1/scripts/installer.sh#L89
I'm currently working on getting OH2 working on my QNAP and just found these lines..

You are symlinking a directory called "configurations" but since OH2 there is "conf". Additionally I don't know whether it would be also save to symlink "userdata".

**Comment by cniweb** [comment]
Hi @thopiekar,

we have changed it in branch 2.0-DSM-6.0:
https://github.com/openhab/openhab-syno-spk/blob/2.0-DSM-6.0/scripts/installer.sh#L91 

Chris

**Comment by acseven** [comment]
fyi, the package's description in Package Manager still mentions "/configurations"

**Comment by cniweb** [comment]
@acseven OK, Thanks!
