### ISSUE TITLE
RRD does not work - java null exception

### ISSUE THREAD

**Issue by drbartz** [openhab/openhab-syno-spk#32]
Hi,

I have some issues trying to use the RRD graphs. They just not show up.

The Exception was:
`
java.lang.NullPointerException: null
openhab.log:    at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[na:1.8.0_60]
openhab.log:    at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) ~[na:1.8.0_60]
openhab.log:    at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[na:1.8.0_60]
openhab.log:    at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:776) ~[na:1.8.0_60]
openhab.log:    at sun.font.SunFontManager$2.run(SunFontManager.java:431) ~[na:1.8.0_60]
`

And also, at the console show:
`
Fontconfig error: Cannot load default config file
`

At the end (after a lot of troubleshooting), I realise that the standard linux fonts is not present on the Sinology.

What I did (is not recommended) was copy 2 folders from my raspberry, with the follow content:

```
etc/fonts/
etc/fonts/conf.d/
etc/fonts/conf.d/10-scale-bitmap-fonts.conf
etc/fonts/conf.d/20-unhint-small-vera.conf
etc/fonts/conf.d/30-metric-aliases.conf
etc/fonts/conf.d/30-urw-aliases.conf
etc/fonts/conf.d/40-nonlatin.conf
etc/fonts/conf.d/45-latin.conf
etc/fonts/conf.d/49-sansserif.conf
etc/fonts/conf.d/50-user.conf
etc/fonts/conf.d/51-local.conf
etc/fonts/conf.d/60-latin.conf
etc/fonts/conf.d/65-fonts-persian.conf
etc/fonts/conf.d/65-nonlatin.conf
etc/fonts/conf.d/69-unifont.conf
etc/fonts/conf.d/80-delicious.conf
etc/fonts/conf.d/90-synthetic.conf
etc/fonts/conf.d/README
etc/fonts/fonts.conf
usr/share/fonts/
usr/share/fonts/liberation/
usr/share/fonts/liberation/LiberationMono-Bold.ttf
usr/share/fonts/liberation/LiberationMono-BoldItalic.ttf
usr/share/fonts/liberation/LiberationMono-Italic.ttf
usr/share/fonts/liberation/LiberationMono-Regular.ttf
usr/share/fonts/liberation/LiberationSans-Bold.ttf
usr/share/fonts/liberation/LiberationSans-BoldItalic.ttf
usr/share/fonts/liberation/LiberationSans-Italic.ttf
usr/share/fonts/liberation/LiberationSans-Regular.ttf
usr/share/fonts/liberation/LiberationSerif-Bold.ttf
usr/share/fonts/liberation/LiberationSerif-BoldItalic.ttf
usr/share/fonts/liberation/LiberationSerif-Italic.ttf
usr/share/fonts/liberation/LiberationSerif-Regular.ttf
usr/share/fonts/liberation/fonts.dir
usr/share/fonts/liberation/fonts.scale
```

After that, the RRD graphics show up as expect. I'm reporting because someone else can have the same issue, and at least have an idea what can be the problem.

My system version was:
- Sinology:

```
uname -a
Linux ds-nas 3.2.40 #7393 SMP PREEMPT Thu Jun 2 19:47:23 CST 2016 i686 GNU/Linux synology_evansport_415play
```
- RRD library:

```
org.openhab.persistence.rrd4j-1.8.3.jar
```
- Raspberry:

```
name -a

Linux OpenELEC2 4.1.18 #1 SMP Mon Feb 29 20:48:22 CET 2016 armv7l GNU/Linux
```

Regards,
##

**Comment by finezza** [comment]
Hi I have the same problem...
You have copied the folders from raspberry but I don't understand where I have to copy on the synology. On my syno I have not 'usr/share/fonts/' and 'etc/fonts/'.
I have to create them?

Thank you!

**Comment by jointerCZ** [comment]
I can confirm that this was working for me on DSM 6.0, but the graphs are broken again after updating to 6.1 DSM.
So i tried to fix it again by copying fonts and configs from Pi system, but the problem is Synology now does have files in /etc/fonts and i cannot get it working.

**Comment by drbartz** [comment]
Agree with JointerCZ. Have to do the same procedure.

I did not mention, but is required a restart of OpenHab to graphics back to work.

```
# uname -a
Linux ds-nas 3.2.40 #15101 SMP PREEMPT Thu Apr 20 03:58:35 CST 2017 i686 GNU/Linux synology_evansport_415play
```

**Comment by drbartz** [comment]
>finezza commented on Oct 16, 2016
>
> Hi I have the same problem...
> You have copied the folders from raspberry but I don't understand where I have to copy on the synology. On my syno I have not 'usr/share/fonts/' and 'etc/fonts/'.
> I have to create them?
> 
> Thank you!

Yes, the folder are the same. You have to create them.

**Comment by jointerCZ** [comment]
For some reason, i cannot get it working again. The Openhab is 2.1.0.004-Snapshot and device DS415+ with DSM DSM 6.1.1-15101 Update 1. This was a simple 5 minute solution for DSM 6.0 and 2.0.x snapshot of the Openhab. Now i spent over 2 hours restarting and copying files with no effect.
