### ISSUE TITLE
1.8.3-DSM6 sitemap 'default' unreachable by user 'openhab'

### ISSUE THREAD

**Issue by pixilarion** [openhab/openhab-syno-spk#33]
I am encountering the following problem on my DS213j:
- my configuration and addons folders are placed in `/volume1/public/Openhab`.

> $ ls -al /volume1/public/OpenHAB/
> total 20
> drwxrwxrwx 4 openhab users 4096 Jul 13 17:57 .
> drwxrwxrwx 4 root    root  4096 Jul 29 14:26 ..
> drwxrwxrwx 2 openhab users 4096 Aug  4 22:16 addons
> drwxrwxrwx 7 openhab users 4096 Aug  4 22:18 configurations
- when I run `start_runtime.sh` inside `/volume1/@appstore/OpenHAB` from the command line **as root** everything work perfectly. The default sitemap is recognised, etc.
- when I start the service form the DSM6 interface, the service starts (confirmed by a `ps aux | grep java`) but shows me an error that the sitemap `default` could not be found. Trying to reach the sitemap with `?sitemap=` results in an identical error.

I have been trying different approaches (copying the configuration files in `/volume1/public/OpenHAB/`, chown as openhab/chgrp as users, etc.) but so far no luck.

This means that I have to run OpenHAB every time it stops (reboot, power failure,...) manually from the console, plus I have to run OpenHAB as root, which I don't like at all.

Anyone any ideas how to fix this?
##

**Comment by cniweb** [comment]
Hi @pixilarion 

I thinks this was a permission problem.
Can you check the permissions of your openhab folder: `ls -al /volume1/public/`

Chris
