### ISSUE TITLE
version 1.8.3

### ISSUE THREAD

**Issue by roysv** [openhab/openhab-syno-spk#34]
I'm running this on Synology DSM 5.2-5644 Update 5 (XPenology DS3615xs).

When I start the package from synology web interface it will not start properly as long as openhab is the daemon_user, if I change to root as the daemon_over then it starts.

second thing is that the your timezone fix does not check for summer time, so all log entries is 1 hour wrong for me. 
##

**Comment by cniweb** [comment]
Hi @roysv 

which package do you use?

Chris

**Comment by roysv** [comment]
Sorry late response: OpenHAB-1.8.3-syno-noarch-0.001.spk

**Comment by cniweb** [comment]
Have you the /public/openhab/ folder or not (check the rights)?
