### ISSUE TITLE
No Service created after installation

### ISSUE THREAD

**Issue by Skostrub** [openhab/openhab-syno-spk#35]
DS  213j DSM6 6.0.2

Beta 3 after installation shows "Running in GUI"
WebUI is not working

if I do
su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start.sh"
I get "su: warning: cannot change directory to /var/services/homes/openhab: No such file or directory
"

I can help with testing. I need this stuff to be up again. 1.8 was great!
##

**Comment by cniweb** [comment]
Hi @Skostrub 

I create this days a new release for 2.0-SNAPSHOT.
Can you testing, please?

Thanks,
Chris

**Comment by Skostrub** [comment]
Yes, sure!

Thanks for your efforts a lot.


BR, Sergei


Christian Häussler <notifications@github.com> 9 октября 2016 г. 22:51:50 
написал:

**Comment by Baumi1245** [comment]
2.0-SNAPSHOT-DSM6 not working at all
only 3 files are installed at /volume1/@appstore/OpenHAB2  (start_debug_runtime.sh, start_runtime.sh, stop_runtime.sh)

To get beta3 running i had to set the rights to r/w of the public folder for openHAB2 and also set the owner of the files there to openHAB2.

**Comment by Skostrub** [comment]
A can also confirm that 2.0-SNAPSHOT-DSM6 is not alive yet.

No start.sh file installed

Start/stop in GUI shows "Running" but it is far from truth.
Log folder is not created due to permissions restrictions.

In terminal mode:
root@DS:~# su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start_runtime.sh"

mkdir: cannot create directory ‘logs’: Permission denied
find: `server': No such file or directory
Launching the openHAB runtime...
/var/packages/OpenHAB2/target/start_runtime.sh: line 25: /var/services/homes/openhab/.daemon.pid: Permission denied

**Comment by Baumi1245** [comment]
Looks like there is a "/" to much in the download-path (the last one):
DOWNLOAD_PATH="https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/"

But i still can´t get it running - maybe because of the rights, owner and group within the .sbk?!
Who is "travis"???  ;-)

CU

**Comment by Baumi1245** [comment]
Yes, that did it - just extrakt the .sbk from the zip and install it....

[OpenHAB-2.0-SNAPSHOT_a-DSM6-syno-noarch-0.002.zip](https://github.com/openhab/openhab-syno-spk/files/521593/OpenHAB-2.0-SNAPSHOT_a-DSM6-syno-noarch-0.002.zip)

**Comment by Skostrub** [comment]
Installed!

But still not working.
Any help is much appreciated.

Do I need to copy manually addons and conf?
This folders are empty now.

**Comment by Baumi1245** [comment]
You need the Folders
/volume1/public/OpenHAB2/conf
/volume1/public/OpenHAB2/addons
to work with i.e. openHab Designer.

No need to install addons manualy - the can be installed from the Paper UI.
Copy your old config - maybe it already works, maybe not - im new at openHab. I added Things/Items with the Paper UI and createt rules with the Designer.

1. uninstall OpenHAB
2. create folders
3. install OpenHAB
4. stop OpenHAB
5. give OpenHAB the rights to R/W the folder public
6. start OpenHAB
7. wait one or two minutes
(8. make OpenHAB the Owner of /volume1/public/OpenHAB2 - maybe you don´t have to, then please tell me)

@Skostrub 
If this doesn´t help, tell what exactly is not working.
Please with a screenshot, so others can learn.... THX

BTW: @cniweb 
Why "public" and nothing like "/volume1/SmartHome/OpenHAB2"?

**Comment by cniweb** [comment]
Hi @Baumi1245 

`public` comes from DSM <= 5.2
I update the DSM 6 package to `/volume1/SmartHome/OpenHAB2`,
and I fix the `DOWNLOAD_PATH` with no `/` at end,
and I fix the start-script to `start_runtime.sh`, OK?

Thanks,
Chris

**Comment by Baumi1245** [comment]
Hallo und erstmals danke für deine Bemühungen!


Ich glaube irgendwo gelesen zu haben, daß du keine Syno hast....
ich schreib dir jetzt mal auf deutsch - in englich krieg ich die Menge 
nicht hin ;-)


In meiner Installations-Anleitung habe ich natürlich was vergessen!
aber von vorne:

Installiere ich *ohne *die Ordner in "public" werden "addons" und "conf" 
in "@appstore" installiert - mit *allen Dateien und Ordnern* die 
mitgeliefert werden.


Installiere ich mit den Ordnern  "/volume1/public/OpenHAB2/conf" und 
"/volume1/public/OpenHAB2/addons" wird bei der installation auf diese 
Ordner verlinkt aber dort keine weiteren Daten abgelegt, da ja OpenHab 
noch keine Rechte hat, dort was reinzuschreiben.
Jetzt sind die Ordner natürlich leer - und das wäre das, was ich 
vergessen habe - ich hab den inhalt dort nochmal gelöscht um von 0 zu 
beginnen - OH läuft, aber man steht halt wirklich mit 0 da und kann 
garnichts mit dem Desinger machen, da dieser seine Dateien braucht.

Könnte man bei der installation nicht einfach noch in "homes/openhab2" 
diese dateien speichern lassen, damit der "Anfänger" diese dann auch hat?
Da dieses Verzeichnis OH gehört sollten dort im Laufe der Installation 
Daten beschrieber werden dürfen; nach einer deinstallation von OH 
verschwindet dieses Verzeichnis wieder - ist also nicht für die 
dauerhafte Auslagerung geeignet.


 1. uninstall OpenHAB -*wegen der korrekten Verlinkung, ansonsten mit 2
    beginnen*
 2. create folders
 3. install OpenHAB
 4. stop OpenHAB
 5. give OpenHAB the rights to R/W the folder public - *jetzt **sollte
    dann ein Anfänger die Daten vom home-ordner kopieren, damit er auf
    den gleichen Stand wie andere Anfänger auf anderen Systemen ist.**
    *
 6. start OpenHAB
 7.

    wait one or two minutes


das wäre jetzt vermutlich der einfachste weg zum Programmieren - 
alternativ: bei start von OH (punkt 6) den Inhalt der ordner in "public" 
prüfen und gegebenenfalls die fehlenden daten vom script reinkopieren 
lassen.



*I update the DSM 6 package to **|/volume1/SmartHome/OpenHAB2|**,*
Danke - ich hoffe in diesem Stadium stört das noch keinen - wenn ich 
mich recht an "public" erinner, war das der Ordner, wo jeder ohne 
Rechtevergabe was reinschreiben konnte - aber der Vorteil ist eh dahin.
Die pfade dann auch in der Programmbeschreibung mit aufnehmen - 
vielleicht kriegst du ja auch obige kurzanleitung rein - ich hab ne 
menge gegooglet um auf das alles zu kommen.

*and I fix the **|DOWNLOAD_PATH|**with no **|/|**at end,*
super - der "travis" darf aber dann auch nicht mehr der besitzer der 
dateien sein!

*and I fix the start-script to **|start_runtime.sh|*
da weiß ich jetzt nicht, für was das gut ist, aber ich werde es schon 
sehen :-)


Das größte Problem momentan sehe ich darin, daß die Config, die von der 
PaperUI erstellt wird, nicht in diesen Ordnern landet....


LG Tom


Am 13.10.2016 um 21:13 schrieb Christian Häussler:

**Comment by Baumi1245** [comment]
@cniweb 
Another problem that **could** be caused by the start-script...

OH has the wrong time - my Synology has the correct one.
If i run this:
` rule "zeit2"
when
    Time cron "0 35 11 * * ?"
 then
 pushover ("es sollte 11:35 sein", "Baumi")
 end`
it comes at 13:35

Thank you.... and sorry for hijacking this thread for general installation-problems

**Comment by cniweb** [comment]
Hallo @Baumi1245,

deutsch ist mir auch lieber! 👍 
Also bevor ich eine neue Version baue, mal zur Erklärung:
Ich habe nur eine DS mit DSM 5.2 KEIN DMS 6, kann also DSM 6 Packages nicht testen!
Deshalb gibt es mehrere Branches und Versionen, einmal 1.8.3 und 2.0 und einmal für DSM 6 und einmal für frühere Versionen.

Nun zum eigentlich Problem 2.0 mit DSM 6 oder DSM 5.2?
Ich würde erst einmal 2.0 mit DSM 5.2 fixen, denn dass kann ich auch selbst testen.
Wenn dieses Paket OK ist würde ich es in DSM 6 portieren.

Ist das OK so?

Viele Grüße,
Chris

**Comment by kaikreuzer** [comment]
> deutsch ist mir auch lieber! 

Guys, please note that far more than 50% of our community do not understand German, so whenever possible, stick to English in the public conversations - what you do in private e-mails is of course completely up to you :-)

**Comment by Baumi1245** [comment]
hi @cniweb 
it´s about DSM 6 here - OH 2.0 is running fine so far...
got only a time-problem and the installation is a little bit confusing if you do it the first time.
OH 2.0 points to a new user groupe - so installing should be as easy as possible.

go on with DSM 5.2 and if i can help you with DSM 6, just send me a mail...

cu Tom

**Comment by cniweb** [comment]
Hi,

I think only the configuration folder is relevant with OpenHAB2.
Because the addons are already there or can be installed online.

Now only the question asks where the folder belongs.
You could already create the folder during the installation and assign the appropriate rights.

What do you think?

Chris

**Comment by cniweb** [comment]
Hi @Baumi1245,

what is the different between my package file and yours:
OpenHAB-2.0-SNAPSHOT_a-DSM6-syno-noarch-0.002.zip ???

Chris

**Comment by Baumi1245** [comment]
there is a "/" to much in the download-path
owner and group within the .sbk is no longer travis

**Comment by cniweb** [comment]
@Baumi1245 
OK, how can I change owner and group?
How or in what do I have to change this?

**Comment by Baumi1245** [comment]
are you online with skype? - or check your mail pls

**Comment by Skostrub** [comment]
Hi guys.

Stupid question:
What is the proper Java for OpenHAB in DSM 6.x:
   package Java 8.0.101-011 by Synology inc.
or
   package Java SE Embeded 8 8.0.101-041 by Oracle from custom repo?

My OpenHAB 1.8 in DSM 5.x was running on Java SE

**Comment by Baumi1245** [comment]
I use the one from synology:
![screenshot 5](https://cloud.githubusercontent.com/assets/4786346/19561626/be36b1ec-96d9-11e6-9356-2c184dacede9.jpg)

**Comment by Skostrub** [comment]
Great. Thanks!

Java 8 SE installation was a bit tricky.
I was expecting this from Synology.

Will try to reproduce your installation steps now.
In step 5: give OpenHAB the rights to R/W the folder public
Do you mean give OpenHAB user R/W like: **chown -R openhab.users /volume1/public/**?

**Comment by Baumi1245** [comment]
A new version is coming up these days- safe your time and wait a little...

Am 20.10.2016 15:35 schrieb "Sergei" <notifications@github.com>:

**Comment by Skostrub** [comment]
Ok, thanks.

Btw, there could be sense to implement demo conf in the package
from

https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/openhab-offline-2.0.0-SNAPSHOT.zip

Conf folder is 5.5 KB only

**Comment by cniweb** [comment]
Hi @Skostrub and @Baumi1245 

I updated the `installer.sh`, look here:
https://github.com/openhab/openhab-syno-spk/commit/d0b882a635e8e550da03a353c38fc3c06153aaf7
Is it OK?

Thanks,
Chris

**Comment by Skostrub** [comment]
### Installed build 2.0.0.005-SNAPSHOT-DSM6:

```
# ps axu | grep openhab2
openhab2  5037  0.0  0.1   5672   956 ?        S    09:09   0:00 -sh -c cd /volume1/@appstore/OpenHAB2 && ./start.sh &
openhab2  5039  0.0  0.3   5652  1836 ?        S    09:09   0:00 /bin/sh /volume1/@appstore/OpenHAB2/runtime/karaf/bin/karaf
openhab2  5321 63.7 15.6 255376 79832 ?        Sl   09:09   5:52 /var/packages/Java8/target/j2sdk-image/jre/bin/java -Dopenhab.home=/volume1/@appstore/OpenHAB2 -Dopenhab.conf=/volume1/@appstore/OpenHAB2/conf -Dopenhab.runtime=/volume1/@appstore/OpenHAB2/runtime -Dopenhab.userdata=/volume1/@appstore/OpenHAB2/userdata -Dopenhab.logdir=/volume1/@appstore/OpenHAB2/userdata/logs -Dorg.osgi.service.http.port=8080 -Dorg.osgi.service.http.port.secure=8443 -Djava.awt.headless=true -Djava.endorsed.dirs=/var/packages/Java8/target/j2sdk-image/jre/jre/lib/endorsed:/var/packages/Java8/target/j2sdk-image/jre/lib/endorsed:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/endorsed -Djava.ext.dirs=/var/packages/Java8/target/j2sdk-image/jre/jre/lib/ext:/var/packages/Java8/target/j2sdk-image/jre/lib/ext:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/ext -Dkaraf.instances=/volume1/@appstore/OpenHAB2/runtime/karaf/instances -Dkaraf.home=/volume1/@appstore/OpenHAB2/runtime/karaf -Dkaraf.base=/volume1/@appstore/OpenHAB2/userdata -Dkaraf.data=/volume1/@appstore/OpenHAB2/userdata -Dkaraf.etc=/volume1/@appstore/OpenHAB2/runtime/karaf/etc -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir=/volume1/@appstore/OpenHAB2/userdata/tmp -Djava.util.logging.config.file=/volume1/@appstore/OpenHAB2/userdata/etc/java.util.logging.properties -Dkaraf.startLocalConsole=true -Dkaraf.startRemoteShell=true -classpath .:/var/packages/Java8/target/j2sdk-image/jre/lib:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/boot/org.apache.karaf.diagnostic.boot-4.0.4.jar:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/boot/org.apache.karaf.jaas.boot-4.0.4.jar:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/boot/org.apache.karaf.main-4.0.4.jar:/volume1/@appstore/OpenHAB2/runtime/karaf/lib/boot/org.osgi.core-6.0.0.jar org.apache.karaf.main.Main
root      8746  0.0  0.1   4632   996 pts/3    S+   09:18   0:00 grep --color=auto openhab2
root@DS:~#

```
UI is not active. http://HOSTNAME:8080/start/index is unreacheble
If I stop OH from package manager it still runs ans "ps axu" still shows all 3 processes

Terminal tests:
```
su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start_runtime.sh"
mkdir: cannot create directory ‘logs’: Permission denied
find: `server': No such file or directory
Launching the openHAB runtime...
/var/packages/OpenHAB2/target/start_runtime.sh: line 25: /var/services/homes/openhab/.daemon.pid: Permission denied
root@DS:~# /var/packages/OpenHAB2/target/start_runtime.sh: line 22: logs/openhab.stdout: No such file or directory
```

```

su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start.sh"
Launching the openHAB runtime...
Unable to update instance pid: /volume1/@appstore/OpenHAB2/runtime/karaf/instances/instance.properties (Permission denied)
/var/packages/OpenHAB2/target/userdata/logs/openhab.log (Permission denied)
Unable to update instance pid: /volume1/@appstore/OpenHAB2/runtime/karaf/instances/instance.properties (Permission denied)
```
instance.properties and have permissons 0644
Granting 0777 to both:

```
su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start.sh"
Launching the openHAB runtime...
!SESSION 2016-10-21 09:34:35.944 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=arm, WS=gtk, NL=en_US

!ENTRY org.eclipse.osgi 4 0 2016-10-21 09:34:35.961
!MESSAGE Error reading configuration: /volume1/@appstore/OpenHAB2/userdata/cache/org.eclipse.osgi/.manager/.fileTableLock (Permission denied)
!STACK 0
java.io.FileNotFoundException: /volume1/@appstore/OpenHAB2/userdata/cache/org.eclipse.osgi/.manager/.fileTableLock (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.eclipse.osgi.internal.location.Locker_JavaNio.lock(Locker_JavaNio.java:36)
        at org.eclipse.osgi.storagemanager.StorageManager.lock(StorageManager.java:388)
        at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:701)
        at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:1749)
        at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:1766)
        at org.eclipse.osgi.storage.Storage.<init>(Storage.java:126)
        at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:85)
        at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:75)
        at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
        at org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:24)
        at org.apache.karaf.main.Main.launch(Main.java:250)
        at org.apache.karaf.main.Main.main(Main.java:175)
```

chmod 777  /volume1/@appstore/OpenHAB2/userdata/cache/org.eclipse.osgi/

retry. 
```
 su -s /bin/sh - openhab -c "/var/packages/OpenHAB2/target/start.sh"
Launching the openHAB runtime...
java.lang.RuntimeException: Exception instantiating lock class org.apache.karaf.main.lock.SimpleFileLock
Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : /volume1/@appstore/OpenHAB2/userdata/lock (Permission denied)
        at org.apache.karaf.main.Main.createLock(Main.java:409)
        at org.apache.karaf.main.Main.doMonitor(Main.java:337)
        at org.apache.karaf.main.Main.access$100(Main.java:70)
        at org.apache.karaf.main.Main$1.run(Main.java:328)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.karaf.main.Main.createLock(Main.java:405)
        ... 3 more
Caused by: java.lang.RuntimeException: Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : /volume1/@appstore/OpenHAB2/userdata/lock (Permission denied)
        at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:56)
        ... 8 more
Caused by: java.io.FileNotFoundException: /volume1/@appstore/OpenHAB2/userdata/lock (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:54)
        ... 8 more
```
The shell is running, but there is another lock in  **/volume1/@appstore/OpenHAB2/userdata/lock**
UI is not active

**Comment by Baumi1245** [comment]
Here we go...
Installed it with my existing /volume1/@appstore/OpenHAB2/conf

Steps i had to do, to get the WebUI running:
1. Stop OpenHAB
2. give rights to R/W the folder "public"
![screenshot 7](https://cloud.githubusercontent.com/assets/4786346/19597686/557914f2-9796-11e6-98a0-5548db45953f.jpg)
3. start OpenHAB
4. wait 1 or two minutes

further steps i made:
installed weather binding
![screenshot 9](https://cloud.githubusercontent.com/assets/4786346/19597801/1f3193c8-9797-11e6-8a30-a01d8e323b78.jpg)

time still not working correct

Logfile: [openhab.zip](https://github.com/openhab/openhab-syno-spk/files/544259/openhab.zip)

**Comment by Baumi1245** [comment]
2nd try:
removed **/volume1/public**

installed OH2
![screenshot 6](https://cloud.githubusercontent.com/assets/4786346/19598741/ae375076-979c-11e6-81d7-428588afceb4.jpg)
symlink was created
/volume1/public does not exist

Logfile: [openhab.zip](https://github.com/openhab/openhab-syno-spk/files/544312/openhab.zip)

**Comment by Baumi1245** [comment]
3rd try:
with existing **/volume1/public**

installed OH2
no folders createt in /volume1/public because of missing R/W rights:
![screenshot 7](https://cloud.githubusercontent.com/assets/4786346/19598992/515ca71e-979e-11e6-8d77-99b2b3a10281.jpg)
symlink was created

Logfile: [openhab.zip](https://github.com/openhab/openhab-syno-spk/files/544328/openhab.zip)

**Comment by Skostrub** [comment]
If installation is clear, should Paper UI be accessebble with emty conf folder?

**Comment by Baumi1245** [comment]
No, that doesn´t work - i had to copy at least these files there:
[conf.zip](https://github.com/openhab/openhab-syno-spk/files/544412/conf.zip)

After this it was a little bit tricky to get it working - i had to reinstall oh2 with these files and folders - but mayby i just did not wait long enough - not sure at this point....

**Comment by Skostrub** [comment]
Have no idea, what the hell has happen, but after hanging for several hours Paper UI is online now.

But when I'm trying to install an extension (serial binding for ex.) it shown progressor ring but nothing happens. It's just cycling...

Can anyone confirm that?

**Comment by Baumi1245** [comment]
so it works without the files i postet?

just installed:
Homematic Binding
HTTP Binding
Network Binding
Pushover Action
HABmin

maybe the server was busy?!

Homematic Binding found 142 things within one minute - works fine so far!

**Comment by Skostrub** [comment]
**so it works without the files i postet?**
Yes

The server look VERY busy with empty OH (100% CPU load)
Optimization needed I think.

**Comment by Baumi1245** [comment]
no problem here - i´ve got a DS713 with 2GB extra RAM
![screenshot 9](https://cloud.githubusercontent.com/assets/4786346/19602760/c5354820-97ae-11e6-92e2-9e7fc755b798.jpg)
I had a RAM usage of 40% with the last version....

**Comment by Baumi1245** [comment]
@cniweb 
I just tried to create a folder in volume1 logged in with WinSCP as admin:
```
Befehl 'mkdir "Neuer Ordner"'
fehlgeschlagen mit Beendigungscode 1 und Fehlernachricht
mkdir: cannot create directory 'Neuer Ordner': Permission denied.
```
I don´t think that the installer-script is allowed to.....

**Comment by Baumi1245** [comment]
@cniweb found something interresting:

I downloaded beta4 for windows.
i extractet the zip.
i removed the content of conf.
i started oh - after 7 minutes no webUI.
![screenshot 11](https://cloud.githubusercontent.com/assets/4786346/19619392/41fa2652-9866-11e6-8de0-2d1eaf4dc006.jpg)


i extracted the zip again.
i started oh - webUI after 2 minutes

tried this two times - always the same.
putting the conf back und restarting oh helps, _could_ be more tricky with linux cause of the user and group rights.
wonder how @Skostrub got it working without these files!

**Comment by Baumi1245** [comment]
Back to the Time-Zone problem:
`/volume1/public/OpenHAB2$ cat /etc/synoinfo.conf | grep timezone | cut -f2 -d'"'
Amsterdam
`
![screenshot 12](https://cloud.githubusercontent.com/assets/4786346/19625632/0c654ea0-991e-11e6-9244-bfbc545c6a66.jpg)
So the script reads the time-zone correct.

I also found it here: /usr/share/zoneinfo/Timezone/synotztable.json
` "Amsterdam": {
        "uistring": "(GMT+01:00) Amsterdam, Berlin, Rome, Stockholm, Vienna", 
        "POSIX_TZ": "CET-1CEST,M3.5.0,M10.5.0/3", 
        "gmtoff": 3600, 
        "nameInTZDB": "Europe/Amsterdam"
    }, 
`

hope this helps

**Comment by cniweb** [comment]
Hi guys,

I create a new release without public folder create and timzone fix.

Chris

**Comment by cniweb** [comment]
Hi @Baumi1245,

can you confirm, that in the new release the timezone correct work?

Thanks,
Chris

**Comment by Baumi1245** [comment]
yes, works fine now.

**Comment by cniweb** [comment]
OK, @Baumi1245 and @acseven,
I released a new release without public folder sym-link and z-wave fix:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0.007-SNAPSHOT-DSM6

**Comment by acseven** [comment]
@cniweb Thanks for the update. I don't know if it was all of the install/uninstalls today, but it was a mess to get it back running. This latest SPK installs ok but doesn't make the port permissions fix.
Here's the permissions after install:

> crw------- 1 root root 166, 0 Oct 24 22:00 /dev/ttyACM0

**Comment by Baumi1245** [comment]
yes, working fine!

2016-10-24 19:57 GMT+02:00 Christian Häussler <notifications@github.com>:

**Comment by gooxbe** [comment]
Which port are you using? is it on default port 8080? I can't get OH2 to work on my syno as this port is taken by another application...

**Comment by Baumi1245** [comment]
yes, default ist 8080.
sorry that i can´t help you more.

**Comment by cniweb** [comment]
Hi all,

I released a new release with the new OH2 folder structur (#37), try it, please:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0.008-SNAPSHOT-DSM6

Thanks,
Christian

**Comment by Baumi1245** [comment]
After uninstalling 2.0.0.007 these folders have not been deleted:
![screenshot 41](https://cloud.githubusercontent.com/assets/4786346/20509951/ecba056c-b06c-11e6-9edc-65be8dc1a73c.jpg)
2.0.0.008 was installed, but it was not running. same problem from .006 to .007.

After uninstalling the latest version again, these folders have been deleted and OH2 was able to run.

**Comment by Baumi1245** [comment]
Had some troubles with the 2nd installation (restarting OH2 did not make a difference):
![screenshot 42](https://cloud.githubusercontent.com/assets/4786346/20522794/6aaa471c-b0b2-11e6-8382-e2680d421b2d.jpg)
![screenshot 43](https://cloud.githubusercontent.com/assets/4786346/20522796/6bce251e-b0b2-11e6-8546-254bd6bc2f99.jpg)


**the 3rd installation is working fine now since about 7 hours....**

**Comment by cniweb** [comment]
Hi @Baumi1245,

thanks for testing!
I think the deinstallation process is wrong.
In the next release I plan a update mechanisms, OK?

Chris

**Comment by Baumi1245** [comment]
@cniweb

Updating would be great - but i think uninstalling also has to work....

Thank you, Tom

**Comment by cniweb** [comment]
OK, then I can close this issue?
I open two new issues, once for the uninstall and once for the update, OK?

**Comment by Baumi1245** [comment]
no, we have three: installing with mounting folder "conf" to public/ or elswhere

**Comment by gooxbe** [comment]
Actually, It doesn't install. Can't download openhab-offline-2.0.0-SNAPHSOT.zip with the spk

**Comment by aurelio1** [comment]
Hello everyone. Will there be DSM 5.2 releases again? I still can't upgrade to DSM 6.0 because Zarafa doesn't work anymore on 6.0 and I still have to migrate it to another mail system. So I would need a DSM 5.2 version.
Besides that, I installed all my software on volume2. Most packages ask where to install something, so it might be useful to have this here too. Otherwise I (and others with the same situation) have to check the .spk and replace all volume1 with volume2; that is a bit annoying :-)

**Comment by Baumi1245** [comment]
@gooxbe 
That can´t be; this code is from the install.sh:
```
DOWNLOAD_FILE="openhab-offline-2.0.0-SNAPSHOT.zip"
DOWNLOAD_PATH="https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target"
DOWNLOAD_URL="${DOWNLOAD_PATH}/${DOWNLOAD_FILE}"
```

if you put this together you get:
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/openhab-offline-2.0.0-SNAPSHOT.zip

... so there must be another problem.
Did you check if there is no openHAB2 folder in  /volume1/@appstore/ bevor installing?
if yes, this causes an issue.

**Comment by gooxbe** [comment]
@Baumi1245
Yes, I checked in /volume1/@appstore and even restarted the syno a few times as I'm also playing on domoticz...
I might build it from the sources as I need to change the default http_port...

**Comment by cniweb** [comment]
OK, I close this Issue, we have 4 new Issues:
#15 
#40 
#41
#42
