### ISSUE TITLE
Installation on DSM 6.0.2 fails

### ISSUE THREAD

**Issue by osaether** [openhab/openhab-syno-spk#39]
I am getting this message when doing an install of 2.0.0.008-SNAPSHOT-DSM6 on DSM 6.0.2-8451 Update 4:

Failed to install "openHAB2".
Usage: wget [OPTION]... [URL]...Try `wget --help' for more options. There was a problem
downloading openhab-offline-2.0.0-SNAPSHOT.zip from the official download link, which was
"https://openhab.ci.cloudbees.com/job/openHAB-
Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/openhab-offline-2.0.0
-SNAPSHOT.zip" Alternatively, you may download this file manually and place it in the 'public' shared
folder.

I have also tried to manually download the zip-file to /volume1/public but get the same error

**Comment by cniweb** [comment]
Have your DS internet access?
You can download it from:
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/

Chris

**Comment by osaether** [comment]
Yes it has internet access and I also manually downloaded the zip-file and placed it in /volume1/public folder but got the same error when running OpenHAB-2.0.0.008-SNAPSHOT-DSM6-syno-noarch-0.001.spk one more time.

**Comment by gooxbe** [comment]
+1 here
DSM 6.0.2-8451 Update 5
Synology DS213+ (qoriq)

It's really annoying there is no easy setup for OpenHAB on a syno. I'm "forced" into using Domoticz for now because of this problem and the fact we can't change the port easily (stay on default 8081)

**Comment by cniweb** [comment]
I think, this is a DSM 6.0.2 problem.

**Comment by osaether** [comment]
SOLVED!

I have ipkg installed and ipkg installs an older version of wget and sets it as the default wget package. Uninstaling the ipkg version of wget using this command fixed it for me:

`sudo ipkg remove wget`

After that, installing 2.0.0.008-SNAPSHOT-DSM6 was successful.

**Comment by aurelio1** [comment]
This didn't work for me. I have ipkg installed, but I didn't have wget. I had wget-ssl and removed it, but without success. I keep getting "Failed to install openHAB2".

**Comment by osaether** [comment]
aurelio1: Did you get the same error as I wrote in the first message above? If yes, then log into your DS with ssh and run the wget command at the command prompt. Then you will see any error message from wget. That was how I figured it out. You can see the syntax of the wget command in the install script included in the 2.0.0.008-SNAPSHOT-DSM6 installation file.

**Comment by aurelio1** [comment]
osaether: thank you. Actually I only got the error message "Failed to install", not the reference to wget. But I saw that the installer always tells me that it failed, but in the end it does install, but it takes somehow longer. The "failed to install" is something like a timeout message. Now openhab works :-)
