### ISSUE TITLE
Support update for the package

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab-syno-spk#42]
Support update for the package

**Comment by yphyph01** [comment]
Hi @cniweb,
If that could help you in that "update" issue, please check this post:
https://community.openhab.org/t/how-to-update-oh2-on-synology/17503/5

**Comment by cniweb** [comment]
Hi @yphyph01,

thanks! Can you make a PR, please?

Chris

**Comment by yphyph01** [comment]
Hi @cniweb ,
OK, I've tried to create a PR for this. Please check PR #45 
Please be aware, that it's my very first GIT contribution. not sure if I've correctly done branching, commit and PR ... 
And I'm not a synology package expert ... I know that my original script is running fine in my context, but, to introduce it in a SPK package, the logic have needed some rework.

**Comment by cniweb** [comment]
Hi @yphyph01,

resolve the conflicts in you PR, I can´t merge!

Chris

**Comment by yphyph01** [comment]
Hi @cniweb 
I need some guidance, which conflict are you talking about?

Yann

**Comment by cniweb** [comment]
OK I resolve the conflict. Please test your SPK again.
