### ISSUE TITLE
Package fails to install since openhab has been moved to a single distro

### ISSUE THREAD

**Issue by ivord976** [openhab/openhab-syno-spk#43]
I am getting an error when trying to install the package "There was a problem downloading openhab-offline-2.0.0.SNAPSHOT....".  I think this is due to this announcement (https://community.openhab.org/t/a-single-distro-from-now-on/19903) of a move to a singe distro so there is no offline distro any more.

**Comment by rkrausen** [comment]
Same problem here

Installation after manual download to /volume1/public also failed.

**Comment by aurelio1** [comment]
It's obvious - the package downloads the current distribution. Since the name of the new, single distribution is different, the package cannot download it anymore.
You will have to wait for a new package or change the name in the appropriate file of the package (unpack the .spk and you will find it).

**Comment by rkrausen** [comment]
Thanks for your answer.
Is there an easy way to unpack / change / pack the spk-package?

**Comment by aurelio1** [comment]
Yes. A .spk is actually a renamed .zip file. Open it with the zip unpacker of your choice. I don't currently have access to it but if I remember correctly the file name is in scripts/installer.sh.
You can change the information (I had to change the volume because I have everything in /volume2, not in /volume1), rezip it and load it manually though the Package Center.

**Comment by rkrausen** [comment]
That didn't work for me.
For the new spk the dam shows an error "Wrong Fileformat"
Tested to change the installer.sh on OS X via Finder, via Terminal (nano) and on the DiskStation via Text-Editor.

**Comment by cplpro227** [comment]
Same here... Wanted to reinstall my OpenHAB 2 on DS216play... but now I can't install it. 
Does anybody know when the problem could be fixed? 

I want to continue :(

**Comment by fiblode** [comment]
As mentioned already you can simply adjust the url and the file name in the installer script inside the spk file. After that it was working for me.

I used 7zip to open the spk file. There is a folder called scripts. Inside you find the "installer.sh". Edit this file and update the download file and download path to the following:
DOWNLOAD_FILE="openhab-2.0.0-SNAPSHOT.zip"
DOWNLOAD_PATH="https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target"

Then update/save the changed installer.sh file

After that the spk file could be installed on my Synology...

**Comment by ivord976** [comment]
Works for me too, thanks aurelio1/fiblode.
The script fails to install from the public folder as PUBLIC_ADDONS="/volume1/public" was not defined

**Comment by cplpro227** [comment]
Worked fine! 
Thanks a lot ! @aurelio1 @fiblode

**Comment by ViktorShch** [comment]
Thanks, it works.
I'm a new user. that need for for OH2 work?
i installed OH2 on DS414, but link http://192.168.1.2:8080/start/index not work. 'Unable to access the site'
Maybe, need i to download some files?

**Comment by grubstake** [comment]
With Mac, also unable to unzip/edit as reported/zip, rename as .spk.  Invalid file format message.

Tried editing file with both Textmate and TextEdit.

Tried zip/unzip both in finder and in shell, including re-zipping excluding hidden files:  
zip -r -X OpenHAB-2.0.0.008-SNAPSHOT-DSM6-syno-noarch-0.001.zip OpenHAB-2.0.0.008-SNAPSHOT-DSM6-syno-noarch-0.001

**Comment by cniweb** [comment]
I traft a new release:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0.009-SNAPSHOT-DSM6
Try it, please!

Thanks,
Chris

**Comment by handy80** [comment]
OpenHAB-2.0.0.009-SNAPSHOT-DSM6-syno-noarch-0.001.spk on Synology DS1813+ not working. zip file seems to be downloaded to /volume1/@tmp/ 
maybe because /volume1/public does not exist

**Comment by inspee** [comment]
Also not completely working for me. 
Seems that the service is installed but there is nothing at /volume1/public
Also I am unable to access the UI.
At /volume1/@tmp is an file  openhab-offline-2.0.0-SNAPSHOT.zip but with 0 byte

**Comment by inspee** [comment]
Sorry, my fault. I was not waiting long enough. It took a very very long time after the installation was finished, but after all I have access to the UI now.

**Comment by cniweb** [comment]
Thanks @inspee yes, the wait time is very long...
