### ISSUE TITLE
openHAB2 conf at /volume1/openHAB2/conf does not work

### ISSUE THREAD

**Issue by gorzan14** [openhab/openhab-syno-spk#50]
After installing opemHAB2 the option to put conf at public on Volume1 does not work. Openhab sticks to the conf at @appstore/openHAB2/conf and does not produce simlink to /vlume1/openHAB2/conf.
I can't find the section in install scripts even not in start scripts. For Version 1.8 i finde the section in scripts.

**Comment by yakobe** [comment]
I seem to be having a similar problem. Did you find a solution?

**Comment by cniweb** [comment]
The symlink to the folders was removed from version 2.0. I will re-install it, if it exists, a link is created.

**Comment by cniweb** [comment]
I change the script:
https://github.com/openhab/openhab-syno-spk/commit/fe3c7f61039b3e18f8c778d7fbb4fac439b559ba
@hphde can you review, please.

Thanks,
Chris

**Comment by gorzan14** [comment]
Hi,
Thanks. As far as I Understand you dont need to do all the stuff for addons. It is a subfolder of conf. 

Could you provide the Same Script for 2.0 realese too?

Von meinem iPhone gesendet

**Comment by hphde** [comment]
@cniweb looks good to me

**Comment by gorzan14** [comment]
@yakobe 
I made a symlink :
ln -s /Volume1/public/openHAB2/conf /Volume1/@appstore/openHAB2/conf
or something like that. Hope I remember it right.

**Comment by gorzan14** [comment]
@cniweb could you integrate the install part for conf folder on public also at the stable 2.0 release?

**Comment by cniweb** [comment]
Yes, but first, we need to fix 2.1.0-SNAPSHOT-DSM6 (master)
