### ISSUE TITLE
site can't be reached

### ISSUE THREAD

**Issue by dikkedimi** [openhab/openhab-syno-spk#53]
Hi Guys and girls,

I installed openhab2 on my DS411j using the instructions on the website. Everything went smooth.

I was able to start the software using package center. but the webaddress remained inaccesible. 
![sad](https://cloud.githubusercontent.com/assets/4985685/22423488/27291420-e6f2-11e6-9cdf-48b83a13bd04.png)

as the logs in package center don't really give me any info, and log:tail doesn't either, I'm at a loss to wat to do next. I tried installing the latest release, the beta3, all of these:
![packages](https://cloud.githubusercontent.com/assets/4985685/22423535/641267ba-e6f2-11e6-82db-666b3bdc8313.png)

all give me the same error :(

with one package, running sudo ./start in terminal did change the "inaccesible" status to a 404. but still unable to use the package.

**Comment by cniweb** [comment]
It usually takes quite a while until OH2 is started, especially at the first start.

**Comment by dikkedimi** [comment]
should it take up to 24 hours?

**Comment by dikkedimi** [comment]
Oh never mind, it works on my DS411j :) :D sorry for bothering you, but it is confirmed at least on this model now :)
