### ISSUE TITLE
Cannot install 2.1.0.001 on DS213

### ISSUE THREAD

**Issue by aurelio1** [openhab/openhab-syno-spk#55]
When I try to install the latest version, after uploading the 2.1.0.001 file it says: "Port undefined configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration"
I can't find any port number in the configuration files of the package, so I wonder why it complains (or does it because there is no port configuration, so "undefined"?).
The syno installation log doesn't help. I tried rebooting the DS, no change. I am surprised because at least beta3 worked flawlessly. Any idea anyone?

**Comment by fivetide** [comment]
Port is defined in [Line 10 of INFO](https://github.com/openhab/openhab-syno-spk/blob/master/INFO#L10). it is 8080, same as many others (like sabnzbd).

**Comment by cniweb** [comment]
You must uninstall other packages that use this port.

**Comment by cniweb** [comment]
See #15
