### ISSUE TITLE
openhab user not created

### ISSUE THREAD

**Issue by SparkoUK** [openhab/openhab-syno-spk#59]
Installing OpenHAB-2.1.0.002-SNAPSHOT-DSM6-syno-noarch-0.001.spk on a DS214Play no user openhab was created on install.  Although the package claims to be running it has permission issues.

**Comment by shagkie** [comment]
I have more or less the same problem installing it on a DS415+.  The service said it's running but I can't seem to connect to it via web interface.

**Comment by SparkoUK** [comment]
I wonder if the postinst function is running in the install as it seems to be setting up most of the things that  seem not to have actually happened.

**Comment by jhlweb** [comment]
See post ["https://community.openhab.org/t/synology-diskstation/1446/178 ](https://community.openhab.org/t/synology-diskstation/1446/178 )
there is a problem with downloading the zip file inside of the script.

**Comment by cniweb** [comment]
@SparkoUK can you try my new version:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.004-SNAPSHOT-DSM6

**Comment by shagkie** [comment]
This new "2.1.0.004" snapshot didn't seem to make a difference on my ds415+

**Comment by cniweb** [comment]
OK, I think the problem is the download from cloudbes build result.
The older versions are on bintray and it works...

**Comment by cniweb** [comment]
@SparkoUK and @jhlweb 
Can we close this issue?

**Comment by SparkoUK** [comment]
Yes
