### ISSUE TITLE
Failed to install "openHAB2"

### ISSUE THREAD

**Issue by baqwas** [openhab/openhab-syno-spk#60]
Error message:
> Failed to install "openHAB2".
> Java is not installed or not properly configured. Download and install as described on
> [](http://wp.me/pVshC-z5 )The Synology provided Java _may not work_ with OpenHAB

(italics mine)
Target machine is **DS1513+**
The suggested Java fix at the tinyURL in the message did not work satisfactorily.
Will try again when the next release is pulled at GitHub.
In the meantime, back to work on the **RPi** deployment. :)
Thanks.

**Comment by viragni** [comment]
Which version of Java did you install?

**Comment by jhlweb** [comment]
else see this post [https://community.openhab.org/t/synology-diskstation/1446/178 ](https://community.openhab.org/t/synology-diskstation/1446/178 )

**Comment by cniweb** [comment]
@jhlweb can you try my new version:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.004-SNAPSHOT-DSM6

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by cniweb** [comment]
@baqwas, @viragni and @jhlweb can we close this issue?

**Comment by baqwas** [comment]
Yes, I am fine with closing the issue. Sorry for neglecting to respond
earlier. Regards.
