### ISSUE TITLE
Backups not deleted

### ISSUE THREAD

**Issue by Baumi1245** [openhab/openhab-syno-spk#61]
After installing 2.1.0.004-SNAPSHOT-DSM6 older backups are not deleted:

![screenshot 71](https://cloud.githubusercontent.com/assets/4786346/23994706/799341e6-0a46-11e7-9ee0-9d994b3bc6cb.jpg)

**Comment by Baumi1245** [comment]
by the way....

what sense makes updating OH instead of a fresh installation?
all my settings are gone anyway and backups are spamming my ds.

**Comment by cniweb** [comment]
You are right, the old backups should be deleted after the restore.

**Comment by Baumi1245** [comment]
@cniweb @SchoppAx
Still got a problem here...
there is no data restored - is this correct?

Why use a timestamp?
Why don´t you just create the folder openhab-backup and delete it, before a new update/backup is made?

**Comment by cniweb** [comment]
Good question.
It is not deleted and is equipped with a timestamp so that you can access older backups

**Comment by Baumi1245** [comment]
But this way it is not possible to make an automated restore....

if i write a shell script ore someone writes an .sbk just to restore data, it can´t be found with a timestamp.
it´s really hard to start with every installtion from nearly zero.

why is there no "backup/restore" in the ui???

**Comment by SchoppAx** [comment]
The issue is resolved.

**Comment by SchoppAx** [comment]
Closed #61.
