### ISSUE TITLE
OH does not accept puplic folder

### ISSUE THREAD

**Issue by Baumi1245** [openhab/openhab-syno-spk#62]
OH can´t use the puplic folder with the latest snapshot:

![screenshot 73](https://cloud.githubusercontent.com/assets/4786346/23998206/a9bbc164-0a54-11e7-982c-e0c91498424d.jpg)

Folders are mounted:
![screenshot 72](https://cloud.githubusercontent.com/assets/4786346/23998215/b1ba047a-0a54-11e7-9168-803e8ccdcf78.jpg)
![screenshot 75](https://cloud.githubusercontent.com/assets/4786346/24001157/aabbfeb8-0a5d-11e7-81ef-6b39b014b6bb.jpg)

Rights are given for the folder "public":
![screenshot 74](https://cloud.githubusercontent.com/assets/4786346/23998313/0564aaee-0a55-11e7-945f-22189093a336.jpg)

**Comment by cniweb** [comment]
OK, I think we must give r/w rights for folder /volume1/@appstore/openHAB2/conf

**Comment by Baumi1245** [comment]
This is strange; it worked with this one about a week ago:
https://community.openhab.org/t/synology-diskstation/1446/191?u=dragonfly

Tried that one again - same issue now.
Can it be the build of OH?

can tell me the correct way to give r/w right for the installer-script?
it should be in this part - correct?:
```
 #if configdir exists in public folder -> create a symbolic link
  if [ -d ${PUBLIC_CONF} ]; then
    rm -r ${SYNOPKG_PKGDEST}/conf
    ln -s ${PUBLIC_CONF} ${SYNOPKG_PKGDEST}
  fi
```

**Comment by Baumi1245** [comment]
@cniweb 
r/w for /addons seems to do the job....
but not for /conf - looks the sub-folders have to have r/w too;
i´m gonna test later on - maybe you are faster with giving me some code - did it with DSM-UI meanwhile...

**Comment by Baumi1245** [comment]
Yap - that did it.

So i had to do 2 steps manually:
give the R/W-right to /public within the "Systemsteuerung"
give R/W-rights to /addons, /conf and sub-folders within "File Station"

**Comment by cniweb** [comment]
@Baumi1245 I do it:
https://github.com/openhab/openhab-syno-spk/blob/master/scripts/installer.sh#L105
and here:
https://github.com/openhab/openhab-syno-spk/blob/master/scripts/installer.sh#L112

**Comment by Baumi1245** [comment]
This still does not work
It only gives R/W-rights to /addons, /conf but **not**  for the sub-folders

**Comment by cniweb** [comment]
How can I set it?

**Comment by Baumi1245** [comment]
I don´t know - what has been changed from prev. versions?

I had always to do this:
give the R/W-right to /public within the "Systemsteuerung"

**this one is new since the update-possibility:**
give R/W-rights to /addons, /conf and sub-folders within "File Station"

i have always the latest DSM-version - is it possible that they made some changes?

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by Baumi1245** [comment]
Tried this one: 2.2.0.003-SNAPSHOT
Better, but not perfect: I still have to give give the R/W-rights to /public within the "Systemsteuerung"

**Comment by Baumi1245** [comment]
This is new: there are 3 files within conf/services/

`2017-07-20 11:12:23.166 [WARN ] [g.dispatch.internal.ConfigDispatcher] - Could not process config file 'http.cfg': java.io.FileNotFoundException: /volume1/@appstore/openHAB2/conf/services/http.cfg (Permission denied)
2017-07-20 11:12:23.170 [WARN ] [g.dispatch.internal.ConfigDispatcher] - Could not process config file 'pushover.cfg': java.io.FileNotFoundException: /volume1/@appstore/openHAB2/conf/services/pushover.cfg (Permission denied)`

addons.cfg must be working, as the packages are all installed which are cofigured here.

**Comment by SchoppAx** [comment]
Hi @Baumi1245, 

can you tell us which permissions are given on your `/public,` `/public/openHAB2` and `/public/openHAB2/conf` folder before and after the installation of 2.2.0.003-SNAPSHOT?

On my Syno the user group has access to the public folders and after the installation the openhab2 user will only added to the `/public/openHAB2/addons` and `/public/openHAB2/conf` folders. So if the user group haven't access to the public or openHAB2 folder (I removed the user group), the openhab2 user get a permission denied.

We can set read permissions for the user openhab2 for the folders `/public` and `/public/openHAB2` if necessary. This should solve the problems...

**Comment by Baumi1245** [comment]
Giving R/W rights to the Group within "File Station" to /public/openHAB2 and sub-folders seem to work...
tried other things too - hope this was it.

interessting; .items .rules,... worked without doing this...

To you have a solution for this too?
give R/W-rights to /public for oh within "Systemsteuerung/Gemeinsamer Ordner"


If you speak german, please PM me - it´s much more easy for me to understand and tell you, what i did..

**Comment by cniweb** [comment]
@Baumi1245: You can access our Skype Chat!
