### ISSUE TITLE
link addons and conf data to /volume1/homes/openhab2/

### ISSUE THREAD

**Issue by andreasbisiach** [openhab/openhab-syno-spk#63]
Hello, 

this is a suggestion.
The idea of being able to manage configuration from a share is great but I would suggest the following approach in the spk installer (since you are creating the user openhab2)

Test if conf is found under /volume1/homes/openhab2/
If yes link to it
if not try  /volume1/public/openhab2/
if yes link to it
otherwise keep it to /volume1/@appstore/openHAB2

Same procedure for addons

Lastly,
during uninstallation, do not remove the user openhab2

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by cniweb** [comment]
Is it still relevant?
What do others think about this?

**Comment by Baumi1245** [comment]
/volume1/homes/openhab2/
is deleted if openhab is uninstalled...

no matter what happens... i want to delete these files myselfe.

I still hope, that i can select the installation-folder - I want to have my stuff in "SmartHome" not in "public" 

;-)

**Comment by andreasbisiach** [comment]
Yes still relevant :-)

And yes, do not delete the openhab2 user or the home folder :-)

"
Lastly,
during uninstallation, do not remove the user openhab2
"

**Comment by cniweb** [comment]
This could be requested during the installation and deinstallation.
1. User to be created / deleted
2. Installation folder for config files

**Comment by Baumi1245** [comment]
/volume1/**public**/openhab2/
/volume1/**homes**/openhab2/
/volume1/**SmartHome**/openhab2/

Maybe it´s possible to select the installation folder via Drop-Down (public by default) - so we both have what we want...

**Comment by cniweb** [comment]
@SchoppAx We can use the WIZARD_UIFILES for this:
https://developer.synology.com/developer-guide/synology_package/WIZARD_UIFILES.html

**Comment by cniweb** [comment]
I think it works, so I close this issue?

**Comment by rberger** [comment]
It looks like `conf` and `addons` are not being copied over from `/volume1/@appstore/openHAB` into `/volume1/SmartHome/openHAB/` and then linked back to `/volume1/@appstore/openHAB`

I.E. after I just did a fresh install, `/volume1/@appstore/openHAB/userdata` was properly set up but there was no `conf` or `addons` in `/volume1/@appstore/openHAB/` but they were still in `/volume1/@appstore/openHAB`

It made it difficult to do a manual install of an add-on.

Not sure if this is a bug or feature.

**Comment by cniweb** [comment]
What is the diffrent between `/volume1/@appstore/openHAB/` and `/volume1/@appstore/openHAB` in your comment?
