### ISSUE TITLE
DS1515+

### ISSUE THREAD

**Issue by andoyin** [openhab/openhab-syno-spk#64]
Hello cN you halp me have a package fir ds 1515+?

**Comment by Rene-Auberger** [comment]
If there is no package for your version of DS you might want to consider an alternative approach to install openHAB on your DiskStation which is described here [http://internet-of-things.blog/en/installing-openhab-in-only-2-steps-on-a-diskstation/](http://internet-of-things.blog/en/installing-openhab-in-only-2-steps-on-a-diskstation/)

**Comment by andoyin** [comment]
hello i have installed Debian chroot but, is is does not start 
can you help ? 
https://s.mail.ru/MpdJ/AZWYjZVDJ it is all time starting . загрузка is a Loading

**Comment by andoyin** [comment]
andranik@DS:~$ sudo su -
Password:
root@DS:~# /var/packages/debian-chroot/scripts/start-stop-status chroot
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
root@DS:/#

**Comment by cniweb** [comment]
Hi @andoyin, what is your problem with this SPK package?

**Comment by andoyin** [comment]
1) debian chroot all time loading this is error https://cloud.mail.ru/public/MpdJ/AZWYjZVDJ
2) i cant enter command /var/packages/debian-chroot/scripts/start-stop-status chroot in command line. 

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)

**Comment by Rene-Auberger** [comment]
The bash warning should go away with these two steps (run as root in debain chroot):

1.     Install debconf (i.e. run `apt-get update` then `apt-get install debconf`, as root)
2.     Run `dpkg-reconfigure locales` as root

Optionally you can run `dpkg-reconfigure tzdata`

**Comment by andoyin** [comment]
sudo: su-: command not found
andranik@DS:~$ sudo su -
root@DS:~# apt-get update
-ash: apt-get: command not found
root@DS:~# sudo apt-get update
sudo: apt-get: command not found
root@DS:~# apt-get update
-ash: apt-get: command not found
root@DS:~#
root@DS:~#
root@DS:~#
  cant do it

**Comment by Rene-Auberger** [comment]
You must switch to the new chroot environment first with `/var/packages/debian-chroot/scripts/start-stop-status chroot`. These are all Debian commands. Please see https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot for details.

**Comment by cniweb** [comment]
The installation work now?
Can we close this issue?

**Comment by cniweb** [comment]
@andoyin and @Rene-Auberger Can we close this issue?

**Comment by cniweb** [comment]
I think it works, so I close this issue!
