### ISSUE TITLE
No Items in Rest-API and Habmi and no conf

### ISSUE THREAD

**Issue by Blackei** [openhab/openhab-syno-spk#66]
Hi,
I installed the last  Snapshot and the Folder in Public Will Not be used but the Folder in /volume/@appstore/openHAB2 is missed too. 
Than there are no Items in the Habmini in the Part Rules and the Rest API. When You know the Item You can select them in the Test API but You can't Show all Items.

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by cniweb** [comment]
@Blackei we are released a new version:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.2.0.004-SNAPSHOT
Can you try it, please!

**Comment by cniweb** [comment]
I think it works, so I close this issue!
