### ISSUE TITLE
Installed fresh, says its running but cannot connect

### ISSUE THREAD

**Issue by Ltek** [openhab/openhab-syno-spk#68]
I have installed/uninstalled several times. I tried changing the port (start_runtime.sh) times.  The log always ha one or more of these errors...

Error installing boot features
Exception caught while starting SSH Server
Address already in use

... and many others

I uninstalled all Java instances and installed Oracle 8 latest JDK using Rednoah's installer

I'm running OH2.1 in Docker on Syno but want to run natively.

Any help would be appreciated. Thx

**Comment by aurelio1** [comment]
"boot features"? Does the error appear when you install it (through DSM, I assume) or when you run it? If the latter: Did you switch on the TRACE mode? In which file did you change the port?

**Comment by Ltek** [comment]
I don't know what Trace mode is. changed port in start_runtime.sh

**Comment by cniweb** [comment]
> Exception caught while starting SSH Server
> Address already in use

Is the SSH Port on your Synology free?

**Comment by bcrippsy38** [comment]
Having the same issue with 2.1.0.005-DSM6 but 2.0.0.001-DSM6 works fine. I'm still struggling to get the configuration folder to work in the public share, but would like to be on the latest with it working...

**Comment by bcrippsy38** [comment]
Can someone please help me figure out what I'm doing wrong before I completely give up trying to use openHAB2? I am starting fresh with 2.1.0.008, and reinstalled java as well. my public folder looks like this:
![capture](https://user-images.githubusercontent.com/25467696/28144556-21c2670c-673a-11e7-8f95-62f3a698dc2f.PNG)

Even when I don't use the public/openHAB2/conf folder, openHAB2 still doesn't install correctly. The only files in the folder are:
![capture](https://user-images.githubusercontent.com/25467696/28144594-744989ec-673a-11e7-813f-5687b2c9a195.PNG)

I tried creating an openhab user and still no luck. Early on when I first started playing with openHAB2, the only version i could ever get to install and run properly was an earlier version of 2.1.0.00x. I think it was 4.

Anyone have a walk through tutorial or something? It should be this complicated to install.

**Comment by Elle4u** [comment]
Same here. I think there is an error in the installer. My old installation got deleted and from the new installation only the 3 start/stop-scripts are there.

This is working:
openHAB-2.0.0.001-DSM6-syno-noarch-0.001.spk

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by Elle4u** [comment]
It seems to work for me, so it can be closed in my case.
Thanks for your efforts.
