### ISSUE TITLE
Can not be installed on DS416 - Port undefined or used by other service

### ISSUE THREAD

**Issue by kvlado80** [openhab/openhab-syno-spk#69]
It is related to version OpenHAB-2.1.0.004-SNAPSHOT-DSM6-syno-noarch-0.001.spk. Err msg is: Port undefined or used by other service. What service is already running on which ports?

**Comment by simonattilahun** [comment]
Similar issue here. Synology version installs but dashboard does not load. Might be a port problem. Can someone help how tol solve?
A.

**Comment by Idus** [comment]
Same for me on a **DS412+** - trying to install <_OpenHAB-2.1.0.004-SNAPSHOT-DSM6-syno-noarch-0.001.spk_>

![capture](https://user-images.githubusercontent.com/3735486/27552454-c02ce128-5aa7-11e7-909e-894f3c518eeb.JPG)

Have no clue to where to start to correct this. Wanted to test it on my current DS412+ before I buy and use it properly on a DS916+ (more CPU and RAM). Would have been great to have a look at it.

**Comment by aurelio1** [comment]
Do the following:
1. Unpack the spk
2. change the file named INFO, parameter adminport, to another port number.
3. you re-pack the whole directory
4. retry to install it on Synology

**Comment by cniweb** [comment]
A port should be configurable on installation, see #15

**Comment by Idus** [comment]
Thank you @aurelio1 - that worked just fine. Installation done - although I can only access via https. Now I just need to figure out how to setup my z-wave USB stick and tx433n! :) Thanx for the help!

**Comment by GrizTorr** [comment]
A lot of people have SABnzbd installed on their Synology NAS. 
It uses Port 8080, please change the Port to 8282 for example.

**Comment by cniweb** [comment]
See #15
