### ISSUE TITLE
No Dirs in openHAB2 after install OpenHAB-2.1.0.008-syno-noarch-0.001.spk

### ISSUE THREAD

**Issue by hoggm2** [openhab/openhab-syno-spk#75]
Same issue as others, but this was on what I thought was a stable release. I avoid snapshots as this is for "production" usage.
DSM 6.1.3-15152
415+

I undertook the following steps:
- Shutdown running openhab
- downloaded spk
- Executed upgrade manually from Synology Package Manager - no error messages displayed, or problems flagged in synology logs
- Started openHab. Claimed to be running, but wasn't. No files in directory apart from 3 scripts.
- config files are still present in public folder, but I had taken a precautionary backup anyway.

I also tried removing openhab completely and doing a new install, but that also failed.

Damaging a working installation in this way is "not good"[TM]. Perhaps untill there is a stable upgrade process, it should be setup as a new installation in OH. And let users confirm all is working before manually removing old version.

If I figure out a solution, I will update.

Kind Regards

Martin

**Comment by cniweb** [comment]
New releases:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.005-DSM6

**Comment by SchoppAx** [comment]
@cniweb there is a issue at the 7z command. I created a PR and released a new Version.

https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.1.0.006-DSM6

**Comment by DanNielsen** [comment]
When i try to install openHAB-2.1.0.006-DSM6-syno-noarch-0.001.spk
![openhab - installing openhab-2 1 0 006-dsm6-syno-noarch-0 001 spk](https://user-images.githubusercontent.com/30105329/28304405-bd8a06c0-6b97-11e7-87b8-e1d3d475dd59.jpg)

**Comment by DanNielsen** [comment]
It seems to work :slight_smile: with openHAB-2.1.0.006-DSM6-syno-noarch-0.001.spk it makes the openhab2 user but i can't se any files in "/volume1/Public/openHAB2/conf" or "/volume1/Public/openHAB2/addons".

**Comment by aurelio1** [comment]
I have the same problem ("Get new version Processing openhab-2.1.0.zip") with the latest release, 2.1.0.005-DSM6. @DanNielsen where did you get the .006 version? However they seem to have the same problem. User is created though.

**Comment by DanNielsen** [comment]
Se my link :)

**Comment by SchoppAx** [comment]
Hi @DanNielsen and @aurelio1,

the message "Get new version Processing openhab-2.1.0.zip" only inform you, that the package will be downloaded and extract. If you look at the installer.sh you will see the echo commands.

All files are located at the `/{your_volume}/@appstore/openHAB2` folder.

Please check if openHAB 2 is running on your syno. 
(your_domain:8080/start/index or 
`/{your_volume}/@appstore/openHAB2/start.sh` to see if an instance is running
)

**Comment by DanNielsen** [comment]
The package version is 2.1.0.006 according to the package info
![openhab - package version openhab-2 1 0 006-dsm6-syno-noarch-0 001 spk](https://user-images.githubusercontent.com/30105329/28311682-b44ecfb4-6bb0-11e7-89d3-62c88af47569.jpg)
I through that conf and addons should be in in "/volume1/Public/openHAB2/conf" or "/volume1/Public/openHAB2/addons"?

**Comment by SchoppAx** [comment]
Yeah that's right. 
I added a new Action (for example Mail Action) under Addons and after a few minutes i got a `mail.cfg` inside the `/volume1/public/openHAB2/conf/services` folder.

Seems to work 😇

The source of the bindings, etc. will be located at `/volume1/@appstore/openHAB2/userdata/tmp/mvn/org/...`

**Comment by SchoppAx** [comment]
@DanNielsen now I know what you mean, please check this release:
https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.1.0.007-DSM6

**Comment by DanNielsen** [comment]
Now i get a lot of folders. But i can not see how to change conf for ex. "IHC Binding"? I have installed the Binding using PaperUI, but i can not se any change i /volume1/public/openHAB2/conf/ or/volume1/public/openHAB2/addons/

**Comment by aurelio1** [comment]
SchoppAx: 2.1.0.007 creates the folders for me too (until 006 it didn't), and it creates events.log and openhab.log, but without entries. After that, the process takes a lot of memory, the connection never starts working and everything hangs until I 'kill -9' the JAVA process...

**Comment by SchoppAx** [comment]
@aurelio1 openHAB need 8-10 minutes to start (because of JAVA) on my DS214+. At this time the CPU goes up and down. After that the system runs normally.
What kind of system do you have?

@cinweb released a new release from this repository with my changes. So please take a release from this repository and wait 10 minutes after the installation.

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by hoggm2** [comment]
Excellent - good news guys! For the avoidance of doubt for future readers, is there another identifier (aside from 2.1.0.008) we can use to indicate the working version? would that be d335451?

**Comment by cniweb** [comment]
Good point!
In the future, I will feature working versions with a **-WIP** suffix in the name of the version.
