### ISSUE TITLE
openHAB-2.1.0.010-syno-noarch-0.001.spk = fix permissions

### ISSUE THREAD

**Issue by DanNielsen** [openhab/openhab-syno-spk#77]
openHAB-2.1.0.010-syno-noarch-0.001.spk does not work for me :(
![openhab - fix permissions openhab-2 1 0 010-syno-noarch-0 001 spk](https://user-images.githubusercontent.com/30105329/28304197-dbbc97da-6b96-11e7-8f40-04665d6a7025.jpg)

**Comment by DanNielsen** [comment]
When i uninstall i get this
![openhab - uninstalling openhab-2 1 0 010-syno-noarch-0 001 spk](https://user-images.githubusercontent.com/30105329/28304338-68df08be-6b97-11e7-8912-b05d340e7623.jpg)

**Comment by SchoppAx** [comment]
Hi @DanNielsen,

the openHAB-2.1.0.010-syno-noarch-0.001.spk is only for DSM Users with Firmware 5.2 or lower.
Please select a DSM 6 package.

**Comment by DanNielsen** [comment]
aarhhh... Sorry :( 
But i can't see any files in "/volume1/Public/openHAB2/conf" or "/volume1/Public/openHAB2/addons" when i install openHAB-2.1.0.005-DSM6-syno-noarch-0.001.spk

**Comment by cniweb** [comment]
The installation seems to work with the new release.
Can we close this issue?

**Comment by DanNielsen** [comment]
How can i close it?
