### ISSUE TITLE
openHAB-2.2.0.003-SNAPSHOT does not work :(

### ISSUE THREAD

**Issue by DanNielsen** [openhab/openhab-syno-spk#78]
it does not work :(
openHAB-2.2.0.003-SNAPSHOT-syno-noarch-0.001.spk

UPDATE: After some minuts "openHAB-2.2.0.003-SNAPSHOT-syno-noarch-0.001.spk" started to work! :)

This version worked but has been removed :(
https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.1.0.007-DSM6

**Comment by SchoppAx** [comment]
@DanNielson, I removed my release, because this repository is now up to date.

Please close your issue, because it is solved ;-)

**Comment by DanNielsen** [comment]
How do i close the issue?

**Comment by DanNielsen** [comment]
Fixes #78

**Comment by DanNielsen** [comment]
close #78
