### ISSUE TITLE
Wrong source for distribution-1.8.0-runtime.zip

### ISSUE THREAD

**Issue by stevmark61** [openhab/openhab-syno-spk#8]
https://bintray.com/artifact/download/openhab/bin
This link is targeted in every .spk I've downloaded.
Error 404...

Tried downloading the runtime zip to Diskstation public directory but the package can still not find the file.

Any chance of correcting the link to  working one?

https://dl.bintray.com/openhab/bin/

Or explain to me how I can regenerate the .spk myself so it works?

Mark S.

**Comment by cniweb** [comment]
Hi Mark, 

OK, thanks for your information.
I fix it. 

Chris

**Comment by cniweb** [comment]
Hi Mark,

I have tested it, the link works properly.
But of openhab 2.0 there are no more Beta1.
I'll adjust the!

Chris

**Comment by cniweb** [comment]
Normal Packages work!

OpenHAB Package 2.0.0-beta2 changed.

**Comment by cniweb** [comment]
@stevmark61 Can I close this issue?

**Comment by stevmark61** [comment]
Sorry, yes.
----Original Message----
From : notifications@github.com
Date : 09/02/2016 - 20:55 (EO)
To : openhab-syno-spk@noreply.github.com
Cc : mark@stevensweb.eu
Subject : Re: [openhab-syno-spk] Wrong source for distribution-1.8.0-runtime.zip (#8)
@stevmark61 Can I close this issue?

**Comment by cniweb** [comment]
Thankyou
