### ISSUE TITLE
Install documentation wrong about location of configuration files

### ISSUE THREAD

**Issue by dfrap** [openhab/openhab-syno-spk#80]
The current documentation is both wrong and incomplete about the location of configuration files.  I suggest the following updated text:

The location of the  configuration files varies depending if a shared folder named public exists.  The public folder is created automatically after your Synology NAS is first set up for certain models.  The administrator can also create a public shared folder if desired. Synology does not document what models will automatically create a public folder.  https://www.synology.com/en-us/knowledgebase/DSM/help/DSM/AdminCenter/file_share_desc  

If a public folder exists, the OpenHAB install script will place configuration files on the public folder.  Note that group user must have read/write access or OpenHAB will not be able to access the configuration files.  Use Control Panel, Shared Folders, edit public, Permissions, Local Groups from pull down, and give users Read/Write access.  

If a public shared folder exists, the configuration files are located at:
/volume1/public/openHAB2/conf/

If no public shared folder exists, the configuration files are located at:
/volume1/@appstore/openHAB2/conf/

**Comment by dfrap** [comment]
Typo should be:
If no public shared folder exists, the configuration files are located at:
 /volume1/@appstore/openHAB2/conf/

**Comment by dfrap** [comment]
Typo should be:
If no public shared folder exists, the configuration files are located at:
" /volume1/@appstore/openHAB2/conf/"

**Comment by SchoppAx** [comment]
@cniweb can you please add the recommended text from @dfrap to the documentation for the moment (https://github.com/openhab/openhab-docs/blob/gh-pages/installation/synology.md). 
But without the 

> Note that group user must have read/write access or OpenHAB will not be able to access the configuration files. Use Control Panel, Shared Folders, edit public, Permissions, Local Groups from pull down, and give users Read/Write access.

because it is fixed in the new release.

@dfrap you can use the code tag ``
`/volume1/@appstore/openHAB2/conf`

**Comment by cniweb** [comment]
A new PR that contains your suggestion I have created!

**Comment by dfrap** [comment]
Very good update.   Well formatted and informative.
