### ISSUE TITLE
Problem with pre-release 2.2.0.004-SNAPSHOT

### ISSUE THREAD

**Issue by mistermaek** [openhab/openhab-syno-spk#81]
Hi,
i tried to install the pre release 2.2.0.004-SNAPSHOT on a synology disk station
running the dsm version 4.2 and there comes an error while the installation process that it is only possible on DSM version 6.0 and above.

_openHAB v2.2.0 Synology DiskStation Package for DSM <= 5.2 AND >= 6.0_

Till which version is it possible to install the package?

**Comment by cniweb** [comment]
Should work now:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.2.0.004-SNAPSHOT

**Comment by mistermaek** [comment]
Yes this works now with the new snapshot version 2.2.0.004-SNAPSHOT.
Thx.
