### ISSUE TITLE
openHAB 2 not starting on Synology NAS 209

### ISSUE THREAD

**Issue by mistermaek** [openhab/openhab-syno-spk#83]
Hi there,
i tried also via ssh to start the runtime by the script start.sh but it failed with the following error:

../start.sh: exec: line 6: ../runtime/bin/karaf: not found

Aferwards i check the folder runtime/bin and there is no karaf at all, there is only a contrib folder!

Any ideas?
Thx in advance for your help.

**Comment by cniweb** [comment]
Hi @mistermaek What version of DSM are you using?

**Comment by mistermaek** [comment]
Hi, the DSM Version is 4.2 and the package version is 2.2.0.005-SNAPSHOT.

**Comment by mistermaek** [comment]
anyone an idea why it doesn't work?

**Comment by SchoppAx** [comment]
Hi @mistermaek,

at the moment we are testing the new prerelease 2.2.0.006, which will include a install.log file. We hope that this new implementation will help us to analyze your problem.

You are welcome to join the tests: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.006-SNAPSHOT

Post the new logfile located in /var/packages/openHAB2/install.log (check the log before you close the install wizard)

**Comment by Kondratiy** [comment]
Same bug DSM 5.2-5967

**Comment by SchoppAx** [comment]
@mistermaek and @Kondratiy,

please use the new release and post your `/var/log/openHAB2-install.log` content.

**Comment by mistermaek** [comment]
Hi,
i tried with the new release but still the same behaviour. Installation done successful but not possible to startup the application. I attached the logfile you asked for. 

![grafik](https://user-images.githubusercontent.com/30464944/28995297-c6aaae38-79e5-11e7-8ebc-59118c524dca.png)

**Comment by SchoppAx** [comment]
Yeah, there is an bug by getting the share location on < DSM 6. We have a fix for that coming soon ;-)

**Comment by mistermaek** [comment]
Hi there,
sounds great. Can you saiy approx. when it will be?
If it'll take longer i try to get the whole thing running on a raspberri.
Thx.

**Comment by SchoppAx** [comment]
Hi @mistermaek ,

can you please test this update: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.007-SNAPSHOT

thx

**Comment by mistermaek** [comment]
Hi SchoppAx,
please find attached the log file after trying to run the application.

![grafik](https://user-images.githubusercontent.com/30464944/29031768-8e8ef256-7b8f-11e7-8190-36b7e633bc90.png)

**Comment by SchoppAx** [comment]
Oh, i forgot the exit after the error message.

I changed the container file back to .zip, because the tar command doesn't extract all files under <= DSM 5.2. So you need a tool to extract a .zip container like unzip or 7z. The .spk will check for these two commands. If none of the two is found you become this error.

Do you have unzip installed? Then please open a terminal session and run these command: `echo "$(command -v unzip)"` and post the output.

Or tell me which tool your syno use ;-)

**Comment by mistermaek** [comment]
Hi,
it is both installed. zip and 7z. See the version info of 7z attached.

![grafik](https://user-images.githubusercontent.com/30464944/29038187-14c750f4-7ba7-11e7-861b-bb5ac3c6299b.png)
It is located under /usr/syno/bin/7z

**Comment by cniweb** [comment]
I can confirm this (on DSM 4.2 and 5.2)

**Comment by SchoppAx** [comment]
Ok, this is strange. Can you please run the following commands:
`if [ -x "$(command -v unzip)" ]; then 
  echo "unzip is executable."
fi`
and
`if [ -x "$(command -v 7z)" ]; then
  echo "7z is executable"
fi`

These are the conditions to extract the container.

thx

**Comment by mistermaek** [comment]
Hi,
i tried to run the coomands you send, but it seems that it is not working correctly as the entry pointer  ">" is directly appearing after i press return. I attached also the screenshot. Have i done anything wrong?

![grafik](https://user-images.githubusercontent.com/30464944/29085961-39c56704-7c71-11e7-9b39-79d94b0aa8e9.png)

**Comment by SchoppAx** [comment]
Sorry, you have to write it line by line
```bash
if [ -x "$(command -v unzip)" ]; then
  echo "unzip is executable."
fi
```
or add a semicolon
```bash
if [ -x "$(command -v unzip)" ]; then echo "unzip is executable."; fi
```

**Comment by SchoppAx** [comment]
The `command` command is unknown on DSM 4, 5.

We fixed it, but still get the `karaf not found` error. It seams there is a problem by executing the bash script. We will look for a fix.

**Comment by mistermaek** [comment]
@SchoppAx Any news about this issue with the karaf not found error?

**Comment by SchoppAx** [comment]
Hi @mistermaek,

please check out my new pre-release: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.007-SNAPSHOT

I installed this version on my virtual DSM 5 machine. karaf is now there. 
Now I get the error that the Port 8080 is already in use. At the moment I haven't time to check the VM. 

So please run the package on your DS :-)

**Comment by SchoppAx** [comment]
Ok, 

openHAB is running on DSM 5, but this line https://github.com/SchoppAx/openhab-syno-spk/blob/a616c0107486e6c0d4042ad1ed66c844b5c6d201/scripts/start-stop-status.sh#L84 doesn't work on DSM 5. 
`ps | grep "openhab2.*java" | awk '{print $1}'` will work 😒

**Comment by SchoppAx** [comment]
@mistermaek this pre-release work now on my DSM 5.2 VM: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.007-SNAPSHOT

**Comment by mistermaek** [comment]
Hi SchoppAx,
thanks a lot. It works now. The only thing left is that i do not reach the configuration under http://myip:8080.
But this can also be that some program on the nas is blocking this port already.
