### ISSUE TITLE
start problem on DSM 6.1.3-15152 Update 3

### ISSUE THREAD

**Issue by rkrausen** [openhab/openhab-syno-spk#86]
Since update to "DSM 6.1.3-15152 Update 3" openHAB2 won't start.
Tested with 2.2.0.006 & 2.2.0.007

It seems there is a problem with start-stop-status.sh since the update.
Starting openhab via ssh and start.sh still works.

**Comment by SchoppAx** [comment]
Hi @ms777 

there is a problem on DSM 6.1.3-15152 Update 3 to start openhab as background process.
We are looking for a fix...

**Comment by SchoppAx** [comment]
Hi guys,

please checkout these pre-release: https://github.com/SchoppAx/openhab-syno-spk/releases/tag/2.2.0.007-SNAPSHOT

If there are errors, please post the log files from /var/log/openhab-install.log or /var/log/openhab-start-stop.log

**Comment by rkrausen** [comment]
This pre-release works.
Service startup without problems.

Only missing since 2.2.0.006 -> Log-Link in DSM Package Manager shows an empty log-file
