### ISSUE TITLE
Install problem with 2.2.0.006-SNAPSHOT-WIP

### ISSUE THREAD

**Issue by igorrobertifoc** [openhab/openhab-syno-spk#90]
Hello,
I try to install on DS216 play without any problem, but whne I start there is this error:

2017-09-09 10:07:51.953 [WARN ] [org.jline                           ] - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2017-09-09 10:07:52.048 [WARN ] [org.jline                           ] - Unable to retrieve infocmp for type vt102
java.io.IOException: Cannot run program "infocmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:?]
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547) ~[?:?]
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:160) ~[?:?]
	at org.jline.terminal.impl.DumbTerminal.

**Comment by SchoppAx** [comment]
Please have a look on #86

**Comment by igorrobertifoc** [comment]
Thanks,
I installed the 2.2.0.007, the log is empty but the webpage is always blank.

**Comment by igorrobertifoc** [comment]
I have a problem with a USB KEY ZWAVE on synology, I found a thread that wrote

Additionally it’s needed to allow the java environment to access the serial port of the connected peripheral. Therefore the following setting has to be added/adapted on your system in file /etc/default/openhab2:

EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0:/dev/ttyS0:/dev/ttyS2:/dev/ttyACM0:/dev/ttyAMA0"

Do you know where I can write this?
Thank you

**Comment by ms777** [comment]
I also installed the 2.2.0.007. Everything works fine. I did this:
````
1. Install the package, but do not check the box "run after installation"
2. sudo chown -hR openhab2:users /volume1/public/openHAB2
3. Then run the package
````

**Comment by igorrobertifoc** [comment]
Thank you,
I tryed to reinstall with the permission but in my case doesn't work.

The problem is Java I think, but I don't know where write EXTRA_JAVA_OPTS

Another strange thing is that my folder /public/OpenHAB2 is empty after the installation and initialisation.

**Comment by ms777** [comment]
please check the spelling, it must be /volume1/public/openHAB2, not OpenHAB2

The folders conf and addons must be already present, when OH is installed, to be used.

For the USB port access - this is just guessing - you may try this
````
chmod 777 /dev/ttyUSB0
````
and for the other devices

**Comment by SchoppAx** [comment]
All of these settings will be set by the install.sh during the installation.

Please check the log file /var/log/openHAB-install.log if something is skipped or went wrong.

We set the permissions for the public/openHAB2 folder via Synology ACL. If the folder already exists in Linux permission mode, this command failed.

**Comment by igorrobertifoc** [comment]
Thanks,
the folder is /volume1/public/OpenHAB2 , I will try to rename
I try the chmod 777 and changed the error : OFFLINE - BRIDGE_OFFLINE Controller is offline

This is my log file:

`
ash-4.3# cat /var/log/openHAB2-install.log
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:10:05:59

Set instance variables...
  primary: /volume1
  share:   /volume1/public
  oh:      /volume1/public/openHAB2
  backup:  -backup-201709
done
Start preinst...
  Get new version
  Processing openhab-2.2.0-SNAPSHOT.tar.gz
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:10:06:08

Set instance variables...
  primary: /volume1
  share:   /volume1/public
  oh:      /volume1/public/openHAB2
  backup:  /volume1/@appstore/openHAB2-backup-201709
done
Start postinst...
  Create 'openhab2' daemon user
  Install new version
  Create conf/addon links
  Fix permissions
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:10:35:06

Set instance variables...
  primary: /volume1
  share:   /var/services/homes
  oh:      /var/services/homes/openhab2
  backup:  /volume1/@appstore/openHAB2-backup-201709
done
Start preuninst...
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:10:35:16

Set instance variables...
  primary: /volume1
  share:   /var/services/homes
  oh:      /var/services/homes/openhab2
  backup:  /volume1/@appstore/openHAB2-backup-201709
done
Start postuninst...
  Daemon user folder '/var/services/homes/openhab2' not found - nothing deleted
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:14:43:20

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  port:    8080
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB2
  backup: -backup-201709
done
Start preinst...
  Found java executable in PATH
  Java version 1.8.0_121
  Version is more than 1.8
  The User Home service is enabled. UH_SERVICE=yes
  The shared folder '/volume1/public' exists.
  Get new version
  Processing openhab-2.2.0-SNAPSHOT.zip
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:14:43:26

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  port:    8080
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB2
  backup: /volume1/@appstore/openHAB2-backup-201709
done
Start postinst...
  Create 'openhab2' daemon user
  Install new version
    Extract openhab-2.2.0-SNAPSHOT.zip
    Move files to /volume1/@appstore/openHAB2
  Fix permissions
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:20:27:01

Set instance variables...
  public:
  smarthome:
  home:
  tmp:    /volume1/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab2
  backup: /volume1/@appstore/openHAB2-backup-201709
done
Start preuninst...
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:20:27:12

Set instance variables...
  public:
  smarthome:
  home:
  tmp:    /volume1/@tmp
  share:  /var/services/homes
  oh:     /var/services/homes/openhab2
  backup: /volume1/@appstore/openHAB2-backup-201709
done
Start postuninst...
  Daemon user folder '/var/services/homes/openhab2' not found - nothing deleted
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:20:28:05

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  port:    8080
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB2
  backup: -backup-201709
done
Start preinst...
  Found java executable in PATH
  Java version 1.8.0_121
  Version is more than 1.8
  The User Home service is enabled. UH_SERVICE=yes
  The shared folder '/volume1/public' exists.
  Get new version
  Processing openhab-2.2.0-SNAPSHOT.zip
done
#### S T A R T  -  o p e n H A B  S P K ####
2017-09-09:20:28:13

Set instance variables...
  public:    true
  smarthome: false
  home:      false
  port:    8080
  tmp:    /volume1/@tmp
  share:  /volume1/public
  oh:     /volume1/public/openHAB2
  backup: /volume1/@appstore/openHAB2-backup-201709
done
Start postinst...
  Create 'openhab2' daemon user
  Install new version
    Extract openhab-2.2.0-SNAPSHOT.zip
    Move files to /volume1/@appstore/openHAB2
  Fix permissions
done
ash-4.3#
`

**Comment by igorrobertifoc** [comment]
Ok, now it's working. I think every time I disconnect the usb key I have to set chmod 777.

Now I don't find where are rules the folder  /public/OpenHAB2 i is always empty. How can I find?

**Comment by igorrobertifoc** [comment]
found on \volume1\appstore\openHAB2

**Comment by cniweb** [comment]
OK, can we close this issue, now?
