### ISSUE TITLE
2.2.0.007-SNAPSHOT - 2017-09-17 pre-release will not install

### ISSUE THREAD

**Issue by rkrausen** [openhab/openhab-syno-spk#93]
Hi,

the pre-release from last night won't install. In the package manager the "Next" Button won't work on license screen.

**Comment by cniweb** [comment]
What is your environment (DS)?

**Comment by rkrausen** [comment]
DS-916+
DSM 6.1.3-15152 Update 4

The 2.2.0.007-SNAPSHOT before (05.09.2017) works.

**Comment by cniweb** [comment]
@SchoppAx Can you please take a look?
DSM 4.2-3259 and DSM 5.2-5644 works...

**Comment by Baumi1245** [comment]
same here:
2.2.0.007-SNAPSHOT - official
DS713+ / DSM 6.1.3-15152 Update 1

**Comment by mariobrx** [comment]
I just installed 2.2.0.007-SNAPSHOT without any problem
DS414j / DSM 6.1.3-15152 Update 4

**Comment by SchoppAx** [comment]
@rkrausen  and @Baumi1245 

you have checked the license box and can't select the "Next"-Button?
Is the Button still disabled?
In which language is the wizard displayed?
Is the package manager trust level still correct?

I can install the release with DSM 6.1.3-15152 Update 4 and english system language.

Please download the release and try again.

**Comment by rkrausen** [comment]
you have checked the license box and can't select the "Next"-Button? -> YES
Is the Button still disabled? -> YES
In which language is the wizard displayed? -> german
Is the package manager trust level still correct? -> YES

After changing the DSM language to english the installation works !

**Comment by Baumi1245** [comment]
...after checking the licence box the "weiter" button is free - but nothing happens when i push the button...

**Comment by SchoppAx** [comment]
A clear install of 2.2.0.007-SNAPSHOT works on each system language.
An update of 2.2.0.007-SNAPSHOT dosen't work, the "Next" button on license screen does't react. (Only on german system language)

For now you can change your language. 
I will look for a fix.

**Comment by SchoppAx** [comment]
yep, a comma too much^^

I have created a new PR.
