### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by soylant** [openhab/openhab-syno-spk#95]
Hi

I can install 2.2.0.007-SNAPSHOT package on my Synology DS916+ without any problem, but I get a blank screen when trying to access Openhab after...

**Comment by vlczak** [comment]
Same here with openHAB-2.1.0.008-DSM6-syno-noarch-0.001.spk
openHAB2 is up and running (I can also SSH in), but I can't access OH2 via web interface http://take.ms/Fm6m3

**Comment by rboe** [comment]
Had the same problem with 2.2.0.007-SNAPSHOT on my Synology DS916+.

Problem was probalby, that I had not only Java 8 but also Java Embedded version installed (according to older instructions).

So I 
- uninstalled Java 8, JAVA Embedded, openHAB2.
- installed "Java8"
- opened "Java 8" and followed instructions to update with new version from oracle
- installed openHAB2

-> Now it works for me.

**Comment by soylant** [comment]
your the man.. it is all working now :-)

**Comment by cniweb** [comment]
OK, can we close this issue?

**Comment by soylant** [comment]
Yes you Can glose this issue
