### ISSUE TITLE
minor typos in UI

### ISSUE THREAD

**Issue by ms777** [openhab/openhab-syno-spk#96]
openhab-syno-spk/WIZARD_UIFILES/install_uifile,  
openhab-syno-spk/WIZARD_UIFILES/upgrade_uifile:
inculde => include

openhab-syno-spk/WIZARD_UIFILES/install_uifile_de,  
openhab-syno-spk/WIZARD_UIFILES/install_uifile_ger,
openhab-syno-spk/WIZARD_UIFILES/upgrade_uifile_de
openhab-syno-spk/WIZARD_UIFILES/upgrade_uifile_ger:
ornder => ordner

**Comment by cniweb** [comment]
@SchoppAx can you fix this in our PR #94 ?
