### ISSUE TITLE
endless installation process (openHAB-2.2.0.007-SNAPSHOT-syno)

### ISSUE THREAD

**Issue by abraunisch** [openhab/openhab-syno-spk#98]
Up to today is used openHAB 2.1.0.004 on my Synology. To get an newer version i want to install
2.2.0.007 in following steps:

- Login DSM with an Admin-Account
- Deinstallation by the packaging center the old version of openhab
- Donwload the spk file openHAB-2.2.0.007-SNAPSHOT-syno-noarch-0.001.spk
- start the manual installation by the packaging center.

The installation will start but comes not to then end ( see image after one hour )

![grafik](https://user-images.githubusercontent.com/32481571/31119859-b2ab1fc8-a832-11e7-8c6a-ee1036149fd7.png)

I restart my synology, start the installation again but i have the same problem. 

Synology: DSM 214+ , DSM-Version 6.1.3-15152 Update 4
Java: Synology 8.0.121-0013

**Comment by SchoppAx** [comment]
Hi @abraunisch, 
can you post the openhab log-file content? 
Log is located at `/var/log/`

thx

**Comment by abraunisch** [comment]
Hello @SchoppAx ,
thanks for your quick response. The problem is solved by installation of different version of openhab.

Yesterday i spend so many time in the installation and i was very frustraded. So my was decission was to install the openHAB 2.1.0.008. This installtion was ok.
Later i read your message. To find the probelm i tryed the installation of openHAB-2.2.0.007 again.
And was a suprise... Everything is ok :-)

I think the issue can be closed

thx
