### ISSUE TITLE
Mention which port is meant

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-syno-spk#99]
I have no idea which port you are talking about here.. HTTP? HTTPS?
Is this value used for HTTP and HTTPS = (HTTP+1)?

![image](https://user-images.githubusercontent.com/1847437/31311162-981ca70e-aba6-11e7-86d0-aa855618d889.png)

Would be nice if you could make it clear.

**Comment by cniweb** [comment]
HTTP

**Comment by cniweb** [comment]
The description in the wizard should become clearer.
We will edit the description.

**Comment by thopiekar** [comment]
Would be also nice if we could add another page for HTTPS 😉
